### ISSUE TITLE
take a look at unification of the Mocker class and the _Patcher class

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-mock#10]
their distinction seems artifical

**Comment by nicoddemus** [comment]
Hi @RonnyPfannschmidt,

Hmm can you clarify where is this `Mocker` that you mentioned? Or do you mean `MockerFixture`?

If that's the case, that indirection exists only so the user can use an API similar to `unittest.mock`:

```python
mocker.patch.object(obj, 'attr')
```

**Comment by RonnyPfannschmidt** [comment]
we should have a discussion, this relates to #9

**Comment by nicoddemus** [comment]
Closing this and continuing discussion in #9.
