### ISSUE TITLE
Singleton instance mocking

### ISSUE THREAD

**Issue by avanderm** [pytest-dev/pytest-mock#100]
I'd like to present you with the following problem: I have a singleton instance defined by
```python
class Singleton(type):
  _instances = {}
  def __call__(cls, *args, **kwargs):
    if cls not in cls._instances:
      cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
    return cls._instances[cls]

class KeyHandler(metaclass=Singleton):
  def __init__(self, some_var):
    self.keys = self._retrieve_keys(some_var)
    <create some weird data structure using the keys variable, like cyclical rotation of keys>
```

Where the `_retrieve_keys` calls some external API do get some data. My idea is to mock out this method when testing the KeyHandler class. Easily done with:
```python
@pytest.fixture
def key_response():
  return {'key1': 'value1', 'key2': 'value2'}

def test_keys_initialize(key_response, mocker):
  mocker.patch.object(credentials.KeyHandler, '_retrieve_keys', return_value=key_response)
  key_handler = credentials.KeyHandler('some_key')
```

This works, at least if these are your only tests. If however you have another test file that calls a module which instantiates the singleton then the tests will fail (the singleton will have been instantiated with an actual API call and not mocked).

I'm a bit lost to how to proceed with this module. My first hunch would be to instantiate the singleton in conftest.py with the mock API response, such that it can be used in all test files, thus:
```python
@pytest.fixture(scope='module')
def key_response():
  return {'key1': 'value1', 'key2': 'value2'}

@pytest.fixture(scope='module')
def setup_key_handler(key_response, mocker):
  mocker.patch.object(credentials.KeyHandler, '_retrieve_parameter', return_value=key_response)
  return credentials.KeyHandler('some_key')
```
However, `mocker` is function scoped, causing a scope mismatch. Is there a way to proceed? How would you deal with this situation?

Thank you

**Comment by nicoddemus** [comment]
Hi,

Given this singleton implementation, I think the cleanest approach would be to cleanup the singleton instances using [`patch.dict`](http://www.voidspace.org.uk/python/mock/patch.html#patch-dict) before mocking, so it will force `Singleton` to call recreate the singleton and call the API again:

```python
@pytest.fixture
def mocked_key_response(mocker):
  mocker.patch.dict(Singleton, '_instances', clear=True)
  mocker.patch.object(credentials.KeyHandler, '_retrieve_parameter', return_value=key_response)

def test_keys_initialize(mocked_key_response):
  key_handler = credentials.KeyHandler('some_key')
```

Alternatively, I suggest to always cleanup all singleton instances anyway before each test, to ensure you don't leak states between tests:

```python
@pytest.fixture(autouse=True)
def reset_singletons():
  # move this to the root conftest.py file
  Singleton._instances = {}

@pytest.fixture
def mocked_key_response(mocker):
  mocker.patch.object(credentials.KeyHandler, '_retrieve_parameter', return_value=key_response)

def test_keys_initialize(mocked_key_response):
  key_handler = credentials.KeyHandler('some_key')
```

**Comment by avanderm** [comment]
Elegant solution, makes much sense in hindsight, thank you! My tests are passing.
