### ISSUE TITLE
Confusing requirement on mock for Python 2

### ISSUE THREAD

**Issue by ghisvail** [pytest-dev/pytest-mock#101]
The README explicitly list `mock` as a requirement for Python 2, whereas it is listed in `extras_require` in the setup script. Please clarify whether `mock` is an optional or required dependency for `pytest-mock` with Python 2. If optional, please adjust the wording of the README, if required (which I suspect), please list `mock` under `install_requires` for Python 2.

**Comment by nicoddemus** [comment]
Fixed, thanks!
