### ISSUE TITLE
Spyder Not starting

### ISSUE THREAD

**Issue by digantapathak** [pytest-dev/pytest-mock#119]
My spyder just started and close automatically. It shows the following messages.. 
<spyder.otherplugins._ModuleMock object at 0x7fcb757a5780>: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
Traceback (most recent call last):
  File "/home/rusa/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1086, in setup
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
Segmentation fault (core dumped)

**Comment by nicoddemus** [comment]
Hi @digantapathak,

Sorry but this doesn't seem to have anything to do with pytest or pytest-mock. I suggest posting to the [spyder mailing list](https://groups.google.com/forum/#!forum/spyderlib).

**Comment by digantapathak** [comment]
Thanks for your response.. I will post it..
