### ISSUE TITLE
Is it possible to use the mocker with Test classes? are there any examples 

### ISSUE THREAD

**Issue by ldcastell** [pytest-dev/pytest-mock#121]
I'm trying to figure out how to use the mocker within a test class are there some examples on how to do this?

**Comment by wimglenn** [comment]
Is the test class a subclass of `unittest.TestCase` or not?

**Comment by ldcastell** [comment]
Hi @wimglenn, nope is not a subclass of `unittest.TestCase`

**Comment by nicoddemus** [comment]
Then you can use it like any other fixture:

```python
class Test:

    def test_1(self, mocker):
        mocker.patch.object(...)
```

What problems are you having?

**Comment by ldcastell** [comment]
Thanks @nicoddemus, I must have missed something... it is working now
