### ISSUE TITLE
Website Down?  Links currently broken in README.rst

### ISSUE THREAD

**Issue by williammorgan** [pytest-dev/pytest-mock#129]
Hello, 

The following links in README.rst appear to be currently broken as of the time of writing.  An "under construction" page with configuration suggestions appears instead of the content.

http://www.voidspace.org.uk/python/mock/patch.html#patch.
http://www.voidspace.org.uk/python/mock/patch.html#patch-object.
http://www.voidspace.org.uk/python/mock/patch.html#patch-multiple.
http://www.voidspace.org.uk/python/mock/patch.html#patch-dict.

Thanks!

**Comment by nicoddemus** [comment]
Hi @williammorgan,

Thanks for pointing it out.
