### ISSUE TITLE
Mocking open raises AttributeError

### ISSUE THREAD

**Issue by MarcAragones** [pytest-dev/pytest-mock#133]
I am trying to translate `mock_open` [unittest's example](https://docs.python.org/3/library/unittest.mock.html#mock-open) but I get an `AttributeError`:

```python
def test_open(mocker):
    with mocker.patch('__main__.open', mocker.mock_open(read_data='bibble')) as m:
        with open('foo') as h:
            result = h.read()

    m.assert_called_once_with('foo')
    assert result == 'bibble'
```

Output:
```
    def test_open(mocker):
        open_mock = mocker.mock_open(read_data='bibble')
>       with mocker.patch('builtins.open', open_mock) as m:
E       AttributeError: __enter__
```

NOTE: `pytest-mock==1.10.0`

**Comment by nicoddemus** [comment]
The purpose of the `mocker` fixture is to *not* use it as a context manager, otherwise you might as well use `mock.patch` directly. 😉 

Try this:

```python
def test_open(mocker):
    m = mocker.patch('__main__.open', mocker.mock_open(read_data='bibble'))
    with open('foo') as h:
        result = h.read()

    m.assert_called_once_with('foo')
    assert result == 'bibble'
```


See *Note about usage as context manager* in the [README](https://github.com/pytest-dev/pytest-mock/blob/master/README.rst) for more information.

I'm closing this but feel free to follow up with more questions. 👍

**Comment by MarcAragones** [comment]
I had to change `'__main__.open'` with `'builtins.open'`.

**Comment by nicoddemus** [comment]
But did it work otherwise?

**Comment by MarcAragones** [comment]
No, using `'__main__.open'` the mock didn't work as I got the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'foo'
```

But using `'builtins.open'` worked.

**Comment by wdd2421** [comment]
wow, this issue has solved my problem "how to mock open function in python3", thanks a lot!
