### ISSUE TITLE
[Help wanted] Turning context mock into mocker

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest-mock#148]
Sorry if this is a stupid question, but I'm failing to solve this.

I have the following code using `unittest.mock`:
```
mocker.patch.object(main, "_connect")
with mock.patch("main._connect.cached_conn") as mock_db:
    mock_db.cursor().__enter__().fetchall.return_value = expected
```

Which I fail turning into a mocker version.

I've tried:
```
        mocker.patch.object(
            main,
            "_connect.cached_conn.cursor().__enter__().fetchall",
            return_value=expected,
        )
```
and

```
        mocker.patch(
            "main._connect.cached_conn.cursor().__enter__().fetchall",
            return_value=expected,
        )
```
(including versions without calls `()`)

`main.py` contains:
```
import pg8000

def _connect():
    if not _connect.cached_conn:
        _connect.cached_conn = pg8000.connect(
            host=os.environ["DB_ADDRESS"],
            database=os.environ["DB_DATABASE"],
            user=os.environ["DB_USERNAME"],
            password=_fetch_password(),
            port=int(os.environ["DB_PORT"]),
        )
    return _connect.cached_conn

_connect.cached_conn = None

def _execute_query(query):
    conn = _connect.cached_conn
    try:
        with conn.cursor() as cur:
            cur.execute(query)
            conn.commit()
            if query.startswith("SELECT"):
                result = cur.fetchall()
                return result
            return "Success"
    except Exception:
        conn.rollback()
        raise
```

**Comment by graingert** [comment]
```python
mock_db = mocker.MagicMock()
mock_db.cursor().__enter__().fetchall.return_value = expected
mocker.patch.object(main, "_connect", cached_conn=mock_db)
```

**Comment by BeyondEvil** [comment]
Awesome @graingert ! That worked, thank you so much! 👍 

Mind explaining what's happening there? So I can understand what I did wrong? :)

**Comment by graingert** [comment]
Read the note here about use as a context manager: https://github.com/pytest-dev/pytest-mock/blob/master/README.rst#why-bother-with-a-plugin

You're also attempting to patch an already patched object, which is kind of odd. It's better to configure the mock to be applied in your patch before application

**Comment by BeyondEvil** [comment]
> Read the note here about use as a context manager: https://github.com/pytest-dev/pytest-mock/blob/master/README.rst#why-bother-with-a-plugin

Thanks for the link!

> You're also attempting to patch an already patched object, which is kind of odd. It's better to configure the mock to be applied in your patch before application

Yeah, brainfart on my part. 😂
