### ISSUE TITLE
Missing version specifier for `mock`

### ISSUE THREAD

**Issue by sssilver** [pytest-dev/pytest-mock#15]
Hello,

https://github.com/pytest-dev/pytest-mock/blob/master/setup.py#L8 adds `mock` as a dependency without a version specifier.

After yesterday's mock update, we're now getting an installation error:
```
 Downloading pytest-mock-0.7.0.zip
Collecting pytest-cov
  Downloading pytest-cov-1.8.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python2.7/dist-packages (from pytest)
Collecting mock (from pytest-mock)
  Downloading mock-1.1.1.tar.gz (69kB)
Collecting coverage<4.0a1,>=3.7.1 (from pytest-cov)
  Downloading coverage-3.7.1.tar.gz (284kB)
Collecting cov-core>=1.14.0 (from pytest-cov)
  Downloading cov-core-1.15.0.tar.gz
Collecting pbr>=0.11 (from mock->pytest-mock)
  Downloading pbr-1.2.0-py2.py3-none-any.whl (83kB)
Collecting six>=1.7 (from mock->pytest-mock)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: pbr, six, mock, pytest-mock, coverage, cov-core, pytest-cov
  Running setup.py install for mock
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-VRYOyE/mock/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bke1Cs-record/install-record.txt --single-version-externally-managed --compile:
    error in setup command: Invalid environment marker: python_version<"3" or python_version>="3.3"
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-VRYOyE/mock/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bke1Cs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VRYOyE/mock
Removing intermediate container 94340479c1ba
The command '/bin/sh -c pip install pytest pytest-mock pytest-cov' returned a non-zero code: 1
```

Would it be better to specify a dependency version that we know works?

**Comment by nicoddemus** [comment]
Hi,

I didn't look at it in detail, but it seems yesterday's update did break a lot of builds out there. :frowning: 

I'm not sure the best approach is to make `pytest_mock` require known versions though, because fortunately this kind of breakage is rare and frankly I don't want to monitor new `mock`  releases and update `pytest_mock`'s dependency all the time. :sweat_smile: 

People downstream which use `pytest_mock` and `mock` can always pinpoint the dependency themselves.

Cheers,
:beers:

**Comment by sssilver** [comment]
Common sense dictates that at the very least specifying the major version number is reasonable. Most packages don't assume compatibility between major version numbers.

**Comment by nicoddemus** [comment]
> Common sense dictates that at the very least specifying the major version number is reasonable.

I agree in principle, but just adding a package specifier for `mock>=1.0` for `pytest_mock` doesn't add much, IMHO.
