### ISSUE TITLE
pytest introspection with assert_called_once_with()

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-mock#154]
When a mock is called multiple times (with the right arguments, at some point) but only one call is expected:

```python
def test_foo(mocker):
    mock = mocker.Mock()
    mock('foo')
    mock('test')
    mock.assert_called_once_with('test')
```

the output is:

```
>       mock.assert_called_once_with('test')
E       AssertionError: Expected 'mock' to be called once. Called 2 times.
E       
E       pytest introspection follows:

test_x.py:5: AssertionError
```

which is kind of confusing.

**Comment by thisch** [comment]
By confusing you mean that  there is no output after "pytest introspection follows", right?

**Comment by The-Compiler** [comment]
Yep! Ideally, there would be a pytest introspection of all calls there (something like "expected: `[mock.call('test')]`, got `[mock.call('foo'), mock.call('test')]`" or so) - but at least, there shouldn't be a "pytest introspection follows:" if nothing actually follows.
