### ISSUE TITLE
GitHub actions workflow runs unnecessary deploy job

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pytest-mock#158]
Hi friends! 👋 

The GitHub actions workflow runs the deploy job on every push and pull_request and skips over the publish step unless a tag has been pushed according to the [workflow configuration](https://github.com/pytest-dev/pytest-mock/blob/master/.github/workflows/main.yml#L78) and [this run](https://github.com/pytest-dev/pytest-mock/runs/240048269). I think, we can optimize this by creating a separate workflow for [create events](https://help.github.com/en/articles/events-that-trigger-workflows#create-event-create) and filter on the jobs stage rather than the steps stage.

What do you think? 🤖

**Comment by nicoddemus** [comment]
Hi @hackebrot!

Yeah I noticed, but decided to keep it anyway so we test building the package at least. 👍

**Comment by nicoddemus** [comment]
After using GH actions in other projects I agree it is a bit of a distraction for the `deploy` job to run every time. 😁
