### ISSUE TITLE
mocker.patch.object appears to be broken

### ISSUE THREAD

**Issue by binarymason** [pytest-dev/pytest-mock#164]
Python version: 3.7.3

Packages on my machine:

- pytest: 5.2.1
-  pytest-mock: 1.11.1

Testing a patched object method is called will fail using `pytest_mock`:

```python
import pytest
from pytest_mock import mocker

def test_process_is_saved_to_db(mocker):
    with mocker.patch.object(Process, 'save', return_value="it works") as mock_save:
        thing = Process()
        thing.save()

    mock_save.assert_called_once()
```

> AssertionError: Expected 'mock' to have been called once. Called 0 times.

<hr>

But will pass with the exact same signature using `unittest.mock`:

```python
import pytest
from unittest.mock import patch


def test_process_is_saved_to_db():
    with patch.object(Process, 'save', return_value="it works") as mock_save:
        thing = Process()
        thing.save()

    mock_save.assert_called_once()
```

> All tests passed

**Comment by nicoddemus** [comment]
Hi @binarymason,

`mocker.patch.object` is not supposed to be used in a `with` context, please see [Note about usage as a contextmangager](https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager).

**Comment by binarymason** [comment]
Ah, my bad. I need to RTFM.

Would it be helpful for future users if an exception were raised when `mocker.patch.object` is used in a `with` context?

Something along the lines of this?

```py
class MockFixture(object):
    def __enter__(self):
        raise ValueError("with contexts are not supported, etc...")

```

**Comment by nicoddemus** [comment]
Hmmm that's a good idea. Would you like to open a PR in that effect?
