### ISSUE TITLE
Latest pytest (5.3.5) doesn't have config 'mock_use_standalone_module'

### ISSUE THREAD

**Issue by jinpyojeon** [pytest-dev/pytest-mock#180]
It seems pytest doesn't have the config  'mock_use_standalone_module' for 5.3.5? 

I'm currently importing mocker in the conftest.py (which I believe is the right way to use pytest_mock with conftest.py)?

**Comment by jinpyojeon** [comment]
I have also defined 'mock_use_standalone_module' in ini file, but the import still gives me key error:

![image](https://user-images.githubusercontent.com/13807633/73394547-d3e40b80-42ab-11ea-84ce-0a2854533255.png)

**Comment by blueyed** [comment]
Please copy'n'paste the whole traceback - maybe using `--tb=short`.



> I'm currently importing mocker in the conftest.py (which I believe is the right way to use pytest_mock with conftest.py)?

You should just use its fixtures, not import it (usually).

**Comment by jinpyojeon** [comment]
@blueyed Thanks for the quick response!

Here is the traceback using tb=short.

![image](https://user-images.githubusercontent.com/13807633/73398028-acdd0800-42b2-11ea-97e0-f0606cb36692.png)

I have confirmed that pytest.ini file is used by pytest by trying out other configs.

**Comment by blueyed** [comment]
Do you have pytest-mock installed?
Also with copy'n'paste I've meant text.
It would be the best to just paste the whole test run, which would show if "mock" is installed/used also.

**Comment by jinpyojeon** [comment]
`==================================================================== test session starts ====================================================================
platform darwin -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /Users/jjeon656/Wholesale-OrchestrationWebService/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/jjeon656/Wholesale-OrchestrationWebService, inifile: pytest.ini
collected 54 items                                                                                                                                          

tests/unit_tests/test_application.py::test_health_check_success[200-magic_mock_return_value0-expected_response0] ERROR
tests/unit_tests/test_application.py::test_health_check_failure[500-magic_mock_return_value0-expected_response0] ERROR
tests/unit_tests/test_application.py::test_health_check_failure[500-1-expected_response1] ERROR
tests/unit_tests/test_backfill_handler.py::test_backfill_handlers[request_body0] PASSED
tests/unit_tests/test_backfill_handler.py::test_partition_get_s3_prefix_list[request_body0-2019-01-01-2019-01-02-prefix/-expected_list0] PASSED
tests/unit_tests/test_backfill_handler.py::test_partition_get_s3_prefix_list[request_body0-2019-01-01-2019-01-05-prefix/-expected_list1] PASSED
tests/unit_tests/test_backfill_handler.py::test_get_latest_releases[release_feed_and_release0-expected_releases0] PASSED
tests/unit_tests/test_backfill_handler.py::test_get_latest_releases[release_feed_and_release1-expected_releases1] PASSED
tests/unit_tests/test_backfill_handler.py::test_get_latest_releases[release_feed_and_release2-expected_releases2] PASSED
tests/unit_tests/test_backfill_handler.py::test_get_last_failed_backfill_info PASSED
tests/unit_tests/test_correlation_flow.py::test_setup_correlation[truck-roll-batch-dev-cxp-truck-roll-batch-dev-cxp] PASSED
tests/unit_tests/test_correlation_flow.py::test_setup_correlation[simple_json-cable-simple_json-cable] PASSED
tests/unit_tests/test_correlation_metadata_handler.py::test_correlation_metadata[correlation_schema0-expected_correlation_metadata0] PASSED
tests/unit_tests/test_correlation_metadata_handler.py::test_correlation_metadata[correlation_schema1-expected_correlation_metadata1] PASSED
tests/unit_tests/test_elements_object.py::test_elements_feed PASSED
tests/unit_tests/test_elements_object.py::test_elements_object_source PASSED
tests/unit_tests/test_elements_object.py::test_elements_object_event PASSED
tests/unit_tests/test_elements_object.py::test_elements_object_release PASSED
tests/unit_tests/test_elements_object.py::test_elements_object_entity PASSED
tests/unit_tests/test_elements_object.py::test_elements_object_sinks PASSED
tests/unit_tests/test_entity_object.py::UnitTests::test_entity_default_object PASSED
tests/unit_tests/test_event_object.py::UnitTests::test_event_default_object PASSED
tests/unit_tests/test_event_object.py::UnitTests::test_interana_aliases_testing_alias_generation PASSED
tests/unit_tests/test_event_object.py::UnitTests::test_lambda_function_name PASSED
tests/unit_tests/test_event_object.py::UnitTests::test_stream_name PASSED
tests/unit_tests/test_feed_object.py::UnitTests::test_feed_default_object PASSED
tests/unit_tests/test_handler_object.py::UnitTests::test_sink_default_object PASSED
tests/unit_tests/test_helpers.py::test_does_handler_exists[event_counts-handlers0-True] PASSED
tests/unit_tests/test_helpers.py::test_does_handler_exists[event_counts-handlers1-False] PASSED
tests/unit_tests/test_interana_alias_object.py::test_alias_event_source_name[translations_schema0-event,name\norchestrator_realtime,orchestrator_realtime_alias] PASSED
tests/unit_tests/test_interana_alias_object.py::test_bucket_name_from_arn[arn:aws:s3:::timeline-egress-analytics-dev-cxp-timeline-egress-analytics-dev-cxp] PASSED
tests/unit_tests/test_interana_alias_object.py::test_get_interana_event_lookup_file_prefix[benefits_change-events_lookup/2019/04/09/benefits_change_1554812281.234322.csv] PASSED
tests/unit_tests/test_jolt_spec.py::TestJoltSpec::test_create_analytics_jolt_spec PASSED
tests/unit_tests/test_jolt_spec.py::TestJoltSpec::test_create_correlation_jolt_spec PASSED
tests/unit_tests/test_jolt_spec.py::TestJoltSpec::test_create_ingestion_jolt_spec PASSED
tests/unit_tests/test_jolt_spec.py::TestJoltSpec::test_update_date_time_transform_spec PASSED
tests/unit_tests/test_kafka_job_handler.py::UnitTests::test_get_list_of_jobs PASSED
tests/unit_tests/test_kafka_job_handler.py::UnitTests::test_get_list_of_jobs_type_error PASSED
tests/unit_tests/test_lambda_handler.py::test_invoke_partition_lambda PASSED
tests/unit_tests/test_lambda_handler.py::test_invoke_transformation_lambda PASSED
tests/unit_tests/test_release_object.py::test_feed_default_object PASSED
tests/unit_tests/test_release_object.py::test_jolt_update PASSED
tests/unit_tests/test_release_object.py::test_jolt_update_kafka_json PASSED
tests/unit_tests/test_s3_handler.py::test_get_event_retention_rule[test-event/test-90-expected_rule0] PASSED
tests/unit_tests/test_s3_handler.py::test_get_updated_retention_policy[bucket-test-event/test-90-existing_rule0-expected_rule0] PASSED
tests/unit_tests/test_s3_handler.py::test_get_updated_retention_policy[bucket-test-event/test-120-existing_rule1-expected_rule1] PASSED
tests/unit_tests/test_s3_handler.py::test_set_storage_retention_rules_prefix PASSED
tests/unit_tests/test_s3_handler.py::test_set_storage_retention_rules_artifact_calls PASSED
tests/unit_tests/test_s3_handler.py::test_get_updated_retention_policy_exception[bucket-test-test/prefix-90-expected0] PASSED
tests/unit_tests/test_s3_handler.py::test_set_storage_retention_rules_exception_catch PASSED
tests/unit_tests/test_s3_handler.py::test_get_s3_object_key_list[responses0-expected_list0] PASSED
tests/unit_tests/test_s3_handler.py::test_get_s3_object_key_list[responses1-expected_list1] PASSED
tests/unit_tests/test_s3_handler.py::test_get_s3_object_key_list[responses2-expected_list2] PASSED
tests/unit_tests/test_source_object.py::UnitTests::test_feed_default_object PASSED

========================================================================== ERRORS ===========================================================================
_______________________________ ERROR at setup of test_health_check_success[200-magic_mock_return_value0-expected_response0] ________________________________
_pytest/config/__init__.py:1031: in getini
    return self._inicache[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
_pytest/config/__init__.py:1038: in _getini
    description, type, default = self._parser._inidict[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
pytest_mock/plugin.py:206: in mocker
    result = MockFixture(pytestconfig)
pytest_mock/plugin.py:51: in __init__
    self.mock_module = mock_module = _get_mock_module(config)
pytest_mock/plugin.py:28: in _get_mock_module
    config.getini("mock_use_standalone_module")
E   ValueError: unknown configuration value: 'mock_use_standalone_module'
_______________________________ ERROR at setup of test_health_check_failure[500-magic_mock_return_value0-expected_response0] ________________________________
_pytest/config/__init__.py:1031: in getini
    return self._inicache[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
_pytest/config/__init__.py:1038: in _getini
    description, type, default = self._parser._inidict[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
pytest_mock/plugin.py:206: in mocker
    result = MockFixture(pytestconfig)
pytest_mock/plugin.py:51: in __init__
    self.mock_module = mock_module = _get_mock_module(config)
pytest_mock/plugin.py:28: in _get_mock_module
    config.getini("mock_use_standalone_module")
E   ValueError: unknown configuration value: 'mock_use_standalone_module'
___________________________________________ ERROR at setup of test_health_check_failure[500-1-expected_response1] ___________________________________________
_pytest/config/__init__.py:1031: in getini
    return self._inicache[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
_pytest/config/__init__.py:1038: in _getini
    description, type, default = self._parser._inidict[name]
E   KeyError: 'mock_use_standalone_module'

During handling of the above exception, another exception occurred:
pytest_mock/plugin.py:206: in mocker
    result = MockFixture(pytestconfig)
pytest_mock/plugin.py:51: in __init__
    self.mock_module = mock_module = _get_mock_module(config)
pytest_mock/plugin.py:28: in _get_mock_module
    config.getini("mock_use_standalone_module")
E   ValueError: unknown configuration value: 'mock_use_standalone_module'
===================================================================== warnings summary ======================================================================
requests/__init__.py:80
  /Users/jjeon656/Wholesale-OrchestrationWebService/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (3.0.4) doesn't match a supported version!
    RequestsDependencyWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================== 51 passed, 1 warning, 3 errors in 3.14s ==========================================================`

**Comment by jinpyojeon** [comment]
Yup, pytest-mock is installed (v2.0.0)

**Comment by jinpyojeon** [comment]
```
--------------------------------------------------------- fixtures defined from pytest_mock.plugin ----------------------------------------------------------
mocker -- pytest_mock/plugin.py:201
    return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.


------------------------------------------------------ fixtures defined from tests.unit_tests.conftest ------------------------------------------------------
mock_boto3 [session scope] -- tests/unit_tests/conftest.py:12
    tests/unit_tests/conftest.py:12: no docstring available


---------------------------------------------------- fixtures defined from tests.unit_tests.test_helpers ----------------------------------------------------
helpers -- tests/unit_tests/test_helpers.py:10
    tests/unit_tests/test_helpers.py:10: no docstring available


-------------------------------------------------- fixtures defined from tests.unit_tests.test_s3_handler ---------------------------------------------------
elements_obj -- tests/unit_tests/test_s3_handler.py:14
    tests/unit_tests/test_s3_handler.py:14: no docstring available

s3_handler_obj -- tests/unit_tests/test_s3_handler.py:5
    tests/unit_tests/test_s3_handler.py:5: no docstring available


-------------------------------------------------- fixtures defined from tests.unit_tests.test_application --------------------------------------------------
test_application_client -- tests/unit_tests/test_application.py:92
    tests/unit_tests/test_application.py:92: no docstring available


-------------------------------------------------------------- fixtures defined from setup_os ---------------------------------------------------------------
os_environ_fixture -- setup_os.py:26
    setup_os.py:26: no docstring available


------------------------------------------------ fixtures defined from tests.unit_tests.test_lambda_handler -------------------------------------------------
lambda_handler_obj -- tests/unit_tests/test_lambda_handler.py:6
    tests/unit_tests/test_lambda_handler.py:6: no docstring available


------------------------------------------------ fixtures defined from tests.unit_tests.test_release_object -------------------------------------------------
mocked_dependency -- tests/unit_tests/test_release_object.py:17
    tests/unit_tests/test_release_object.py:17: no docstring available

jolt_handler -- tests/unit_tests/test_release_object.py:26
    tests/unit_tests/test_release_object.py:26: no docstring available

Elements -- tests/unit_tests/test_release_object.py:31
    tests/unit_tests/test_release_object.py:31: no docstring available

Release -- tests/unit_tests/test_release_object.py:36
    tests/unit_tests/test_release_object.py:36: no docstring available

request_body -- tests/unit_tests/test_release_object.py:9
    tests/unit_tests/test_release_object.py:9: no docstring available


------------------------------------------------ fixtures defined from tests.unit_tests.test_elements_object ------------------------------------------------
realtime_request_body -- tests/unit_tests/test_elements_object.py:23
    tests/unit_tests/test_elements_object.py:23: no docstring available

batch_request_body -- tests/unit_tests/test_elements_object.py:29
    tests/unit_tests/test_elements_object.py:29: no docstring available

kafka_avro_request_body -- tests/unit_tests/test_elements_object.py:35
    tests/unit_tests/test_elements_object.py:35: no docstring available

Elements -- tests/unit_tests/test_elements_object.py:9
    tests/unit_tests/test_elements_object.py:9: no docstring available


----------------------------------------------- fixtures defined from tests.unit_tests.test_backfill_handler ------------------------------------------------
backfill_handler_cls -- tests/unit_tests/test_backfill_handler.py:20
    tests/unit_tests/test_backfill_handler.py:20: no docstring available

mock_s3_handler_module -- tests/unit_tests/test_backfill_handler.py:25
    tests/unit_tests/test_backfill_handler.py:25: no docstring available

mocked_modules -- tests/unit_tests/test_backfill_handler.py:8
    tests/unit_tests/test_backfill_handler.py:8: no docstring available


----------------------------------------------- fixtures defined from tests.unit_tests.test_correlation_flow ------------------------------------------------
correlation_flow -- tests/unit_tests/test_correlation_flow.py:6
    tests/unit_tests/test_correlation_flow.py:6: no docstring available


----------------------------------------------- fixtures defined from tests.unit_tests.test_interana_handler ------------------------------------------------
elements_obj -- tests/unit_tests/test_interana_handler.py:19
    tests/unit_tests/test_interana_handler.py:19: no docstring available

interana_handler_obj -- tests/unit_tests/test_interana_handler.py:8
    tests/unit_tests/test_interana_handler.py:8: no docstring available


--------------------------------------------- fixtures defined from tests.unit_tests.test_interana_alias_object ---------------------------------------------
interana_handler_object -- tests/unit_tests/test_interana_alias_object.py:8
    tests/unit_tests/test_interana_alias_object.py:8: no docstring available

_UnitTestCase__pytest_class_setup [class scope] -- _pytest/unittest.py:87
    _pytest/unittest.py:87: no docstring available


=================================================================== no tests ran in 0.84s ===================================================================
```

**Comment by jinpyojeon** [comment]
Here's the result of `pytest --fixtures` to show that `mocker` fixture is active

**Comment by nicoddemus** [comment]
Hi @jinpyojeon,

The pytest header you posted shows that `pytest-mock` is not really installed: 

```
cachedir: .pytest_cache
rootdir: /Users/jjeon656/Wholesale-OrchestrationWebService, inifile: pytest.ini
collected 54 items 
```

(You should see a line `plugins: mock-2.0.0` before `collected 54 items` if the plugin was installed correctly and loaded by pytest).

> Here's the result of pytest --fixtures to show that mocker fixture is active

Unfortunately that's misleading because you are importing `mocker` into your `conftest.py` file: this makes the fixture visible to pytest, but not the `mock_use_standalone_module` configuration option (which is installed by the plugin, not the fixture).

----

I suspect it is a problem with how you are installing `pytest-mock`. Are you using a virtual environment? Can you please post the results of `pip list`?

**Comment by jinpyojeon** [comment]
Thanks again @nicoddemus and @blueyed for your help!

As @nicoddemus said, it looks like my install script messed up and I didn't have pytest_mock in the virtualenv! Sorry for not checking for such easy mistake...

To make note for others in the future, it looks like importing mocker is not necessary even if you are using conftest.py.
