### ISSUE TITLE
mock_open working on 3.7, 3.8, but not as expected on 3.6

### ISSUE THREAD

**Issue by pscosta5** [pytest-dev/pytest-mock#185]
```python
from pytest_mock import MockFixture


def test_open(mocker: MockFixture) -> None:
    mock = mocker.patch("builtins.open", mocker.mock_open(read_data="hello\n"))
    with open("file.txt") as file:
        for line in file:
            text = line
    assert text == "hello\n"
```

This passes on 3.7 and 3.8. But fails on 3.6:

```console
E       UnboundLocalError: local variable 'text' referenced before assignment
```

It does pass on 3.6 if I remove the mocker and simply read in a real text file.

Any help is appreciated!

Thanks for the awesome library!

**Comment by nicoddemus** [comment]
Hi @pscosta5,

Thanks for the report and sorry for the delay!

`mocker.mock_open` is just an alias to the builtin `unittest.mock.mock_open` (so you don't have to import it to use it), and I'm afraid there's a bug in `unittest.mock.mock_open` in 3.6.

For example, using standard `unittest.mock`, we get the same results:

```python
from unittest import mock

def test_open() -> None:
    with mock.patch("builtins.open", mock.mock_open(read_data="hello\n")):
        with open("file.txt") as file:
            for line in file:
                text = line
    assert text == "hello\n"
```

So I'm afraid there's really nothing that can be done on pytest-qt's side.

Sorry I don't have a better answer than that!

I'm closing this for now, but feel free to follow up with any questions. :+1:

**Comment by pscosta5** [comment]
Hi @nicoddemus,

No need to apologize! Thanks for the explanation—I should have checked `unittest.mock` before filing the issue 😅.

Thanks again for the great library!

**Comment by nicoddemus** [comment]
No worries, cheers!
