### ISSUE TITLE
Breaking change introduced in MINOR version upgrade

### ISSUE THREAD

**Issue by allrod5** [pytest-dev/pytest-mock#202]
Hi, I've just noticed that there are breaking changes in pytest-mock when upgrading from 3.2.0 to 3.3.0.

The change I've noticed is that importing `MockFixture` from `pytest_mock` now breaks. I understand that the `MockerFixture` type were introduced in 3.3.0 but `MockFixture` was importable from the public API and it would be best to keep it that way for backwards compatibility in 3.x releases. I would only expect breaking of the public API in a MAJOR 4.x release.

**Comment by The-Compiler** [comment]
Can you elaborate on why you needed to import `MockFixture` earlier - was that for type annotations? Despite having a name not prefixed with `_`, for pytest plugins I usually wouldn't consider its module contents public API, as that's typically not how you'd use a plugin. I'd only consider things like fixture names (and whatever is exported via that fixture), commandline arguments, ini options, etc. public.

**Comment by graingert** [comment]
> was that for type annotations?

This does raise an interesting point, now this MockerFixture name is most certainly a public api as it's exported for use in annotations

**Comment by allrod5** [comment]
Hi guys! Yes, I was importing this to type annotate the `mocker` fixture. I'm glad to upgrade to 3.3.0 to have proper support for type annotations though I found it best to report this breaking change for you knowledge.

**Comment by nicoddemus** [comment]
Thanks for the clarification!

Indeed, did not really foresee this use case. Not much can be done at this point thought.

Thanks anyway for the report!

Cheers,

**Comment by allrod5** [comment]
@nicoddemus this is not a big issue for me anyway, though if this affects many users a 3.3.1 version could be released fixing that.
