### ISSUE TITLE
checking call order with pytest-mock

### ISSUE THREAD

**Issue by aabramovrepo** [pytest-dev/pytest-mock#207]
Dear All,

   in the code snippet shown below I would like to test the function call order in the `run()` function, i.e, `f_3` is called after `f_2` that is called after `f_1`:

```
class TestMock:

    def f_1(self) -> None:
        pass

    def f_2(self) -> None:
        pass

    def f_3(self) -> None:
        pass

    def run(self) -> None:
        self.f_1()
        self.f_2()
        self.f_3()

```

is there any way to do this using `pytest-mock`? I have tried to mock the `f_1`, `f_2`, and `f_3` functions in my test file and use `assert_has_calls` with `any_order=False`, however, without success.

Thanks in advance for any help or hints!

Best,
Alexey

**Comment by graingert** [comment]
@aabramovrepo I think this is an issue with cpython mock. mock calls could maintain a counter for this purpose

**Comment by aabramovrepo** [comment]
@graingert thanks for your reply, but it does not help much... do you have an example somewhere for checking call order?

**Comment by nicoddemus** [comment]
Hi @aabramovrepo,

I'm assuming you want to call `run()` and ensure `f1()`, `f2()` and `f3()`

I'm not sure that's easy to accomplish, I've tried with [mock_calls](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.mock_calls) and [method_calls](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.method_calls), but couldn't obtain the behavior you want.
