### ISSUE TITLE
Mock call references updated dict, not point-in-time snapshot of value

### ISSUE THREAD

**Issue by taylorbartley** [pytest-dev/pytest-mock#210]
[examples.txt](https://github.com/pytest-dev/pytest-mock/files/5299787/examples.txt)

In the example provided, when dict `foo` is modified as a result of a method call `make_bar(foo)`, the assertion fails. 
```python
foo = {"foo": "bar"}
foo["bar"] = make_bar(foo)
```
But passes if I instead pass a copy of `foo`:
```python
foo = {"foo": "bar"}
foo["bar"] = make_bar(foo.copy())
```

AssertionError
```sh
E           AssertionError: expected call not found.
E           Expected: make_bar({'foo': 'bar'})
E           Actual: make_bar({'foo': 'bar', 'bar': 'bar'})
E
E           pytest introspection follows:
E
E           Args:
E           assert ({'bar': 'bar...foo': 'bar'},) == ({'foo': 'bar'},)
E             At index 0 diff: {'foo': 'bar', 'bar': 'bar'} != {'foo': 'bar'}
E             Use -v to get the full diff
```

Relevant tools/versions:
```txt
pytest 6.0.2
pytest-mock 3.3.1
Python 3.8.6
```

Is this the intended behavior? Thanks.

**Comment by nicoddemus** [comment]
Hi @taylorbartley,

Thanks for providing an example, however the example is really cluttered to read: it includes tracebacks, logging calls, it is a bit hard to know what's going on.

A good check if there's a problem with `pytest-mock` is to swap `mocker` by plain `unittest.mock`:

```python
 def test_make_foo(mocker):
     with unittest.mock.patch(
         target="good.make_bar", autospec=True, return_value="bar"
     ) as m_make_bar:

         assert make_foo() == {"foo": "bar", "bar": "bar"}
``` 

If you get the same behavior then it is how `unittest.mock` works, if not, it is probably a bug in `pytest-mock`.

**Comment by tirkarthi** [comment]
I guess this is expected and documented : https://docs.python.org/3/library/unittest.mock-examples.html#coping-with-mutable-arguments

There were issues raised to update this and include copying mock : https://bugs.python.org/issue28848 , https://bugs.python.org/issue38346


```python
# /tmp/a.py                          
from unittest.mock import Mock

a = {"a": 1}
m = Mock()
m(a)
a.update({"b" : 2})
m.assert_called_with({"a": 1})
 ```

```
$ python /tmp/a.py
Traceback (most recent call last):
  File "/tmp/a.py", line 7, in <module>
    m.assert_called_with({"a": 1})
  File "/usr/lib/python3.9/unittest/mock.py", line 907, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: mock({'a': 1})
Actual: mock({'a': 1, 'b': 2})
```

**Comment by nicoddemus** [comment]
Thanks @tirkarthi for confirming!

Closing this for now then, let us know if there are still questions.

**Comment by taylorbartley** [comment]
Thanks for the confirmation! It's good knowing that's at least expected behavior.
