### ISSUE TITLE
When tests are duplicated they fail

### ISSUE THREAD

**Issue by paulalex** [pytest-dev/pytest-mock#212]
I am not easily able to create something reproducible but I think this is related to a bug, it seems like the `MockFixture` is somehow persisting mocked methods between tests.

pytest mock version: pytest-mock-3.1.1
pytest version: 5.4.3
Python version: Python 3.8.2

If I duplicate the following method and change the name I would expect it to pass but it actually fails as none of the asserted methods are called:

```
def test_get_sites_cold_old(mocker, event_for_get_sites, context, site_report_data):
    print(f"TYPE: {type(mocker)}")
    ddb_table = "strategy_table"
    expected_response = "SqlServer"
    mock_connection = {}
    os_env = {"DDB_DA_STRATEGY": ddb_table}

    mocker.patch.dict(os.environ, os_env)

    ddb_response = {"Item": {"Strategy": {"S": expected_response}}}

    mocker.patch.object(site_dao.ddb_client, "get_item")

    site_dao.ddb_client.get_item.return_value = ddb_response

    mocker.patch.object(site_dao.SiteListDaoMSSQLImpl, "get_connection")

    site_dao.SiteListDaoMSSQLImpl.get_connection.return_value = mock_connection

    mocker.patch.object(site_dao.SiteListDaoMSSQLImpl, "get_customer_sites")

    site_dao.SiteListDaoMSSQLImpl.get_customer_sites.return_value = site_report_data

    response = site_api.get_customer_sites(event_for_get_sites, context)

    assert len(response) == 1

    _assert_site(response[0])

    site_dao.ddb_client.get_item.assert_called_once_with(
        TableName=ddb_table, Key={"ServiceName": {"S": "Site"}}
    )

    site_dao.SiteListDaoMSSQLImpl.get_connection.assert_called_once_with()

    site_dao.SiteListDaoMSSQLImpl.get_customer_sites.assert_called_once_with(
        mock_connection, event_for_get_sites.get("customer_id")
    )
```

If I comment out this and run the original passes and vice versa which really makes no sense as the tests are separate and as far as I read in the documentation the mocks are supposed to be automatically reset between tests?

I have noticed this issue across my test suite since I first detected it this morning, and in some instances unrelated tests fail because they seem to use pre mocked objects, and if I swap the order of those tests around they pass...

Also interesting is that even though none of the asserted method calls pass, the result is actually returned and the assertions on the mocked data DO pass.

**Comment by paulalex** [comment]
I think this is not a bug with the mocker but a bug with pytest itself because I have managed to get over this by creating a separate test fixture per method, it seems this problem manifests itself when I use the same test fixture for multiple tests.

**Comment by The-Compiler** [comment]
Can't say much without having a runnable example - right now it's a shot in the dark, but I'd suspect your code under test does some kind of caching (or sets globals or something).

**Comment by nicoddemus** [comment]
> I think this is not a bug with the mocker but a bug with pytest itself

It is not impossible, but I would say that's unlikely because the pytest caching mechanism, specially for function-scoped fixtures, is pretty battle tested.

**Comment by paulalex** [comment]
> Can't say much without having a runnable example - right now it's a shot in the dark, but I'd suspect your code under test does some kind of caching (or sets globals or something).

There are no globals in the code... but.. you know you might actually have helped me to identify the issue. Something that completely skipped my mind and makes perfect sense. I have an lru cache decorator on some functions and I think that due to the contexts containing the same request parameters the function calls are being cached.
