### ISSUE TITLE
Spying on functions

### ISSUE THREAD

**Issue by djmattyg007** [pytest-dev/pytest-mock#222]
How can I spy on a function in the current module? For example:

```python
def dummy_fn():
    return 42

fn1 = mocker.spy(dummy_fn)
fn2 = mocker.spy(dummy_fn)
```

This doesn't work right now because `mocker.spy` expects to retrieve a property from an object.

**Comment by nicoddemus** [comment]
Hi @djmattyg007,

That's not currently possible. An easy workaround I suggest is to change that to a method instead.

**Comment by djmattyg007** [comment]
It looks like this is possible without using pytest-mock at all. After a bit of fiddling around and trying to put together incomplete examples from documentation, I was able to make it work like so:

```python
from unittest.mock import Mock


def dummy_fn():
    return 42


mock_fn = Mock(wraps=dummy_fn)
mock_fn.assert_not_called()
result = mock_fn()
assert result == 42
mock_fn.assert_called()
assert mock_fn.call_count == 1
```

**Comment by nicoddemus** [comment]
Interesting, thanks for posting a follow up! I didn't know about the `wraps` argument. 👍 

Closing this for now as it seems you've reached a solution already. 😁
