### ISSUE TITLE
Spy on simple functions (update docs or new implementation?)

### ISSUE THREAD

**Issue by mromagnoli** [pytest-dev/pytest-mock#228]
**Original Issue**
I wanted to spy on a simple function from a module but just by reading the documentation, I only found that `mocker.spy()` was intended to spy on class methods.

 **One solution I found for my case**
So my first attempt was to solve my problem by doing something like this:
Having:
```python
# file in src/some_utils.py
def sum_x_y(x, y):
    return x + y
```
and
```python
# file src/calculator.py
from src.some_utils import sum_x_y

def multiply_n_by_2(n):
    return sum_x_y(n, n)
```
the test:
```python
from src.some_utils import sum_x_y

def test_multiply_n_by_2(mocker):
    spy_on_sum_x_y = mocker.patch("src.some_utils.sum_x_y", side_effect=MagicMock(wraps=sum_x_y))

    assert multiply_n_by_2(2) == 4
    spy_on_sum_x_y.assert_called_once()
```
**After checking pytest-mock tests**
When I was about to try to implement this, I was checking at the project's tests and found the test:
```python
def test_callable_like_spy(testdir: Any, mocker: MockerFixture) -> None:
    testdir.makepyfile(
        uut="""
        class CallLike(object):
            def __call__(self, x):
                return x * 2

        call_like = CallLike()
    """
    )
    testdir.syspathinsert()

    uut = __import__("uut")

    spy = mocker.spy(uut, "call_like")
    uut.call_like(10)
    spy.assert_called_once_with(10)
    assert spy.spy_return == 20
```
so I tried to use it by changing my test as and it went well:
```python
def test_multiply_n_by_2(mocker):
    module_src = __import__("src")
    
    spy_on_sum_x_y = mocker.spy(module_src.some_utils, "sum_x_y")

    assert multiply_n_by_2(2) == 4
    spy_on_sum_x_y.assert_called_once()
```

**Question (TL;DR)**
Should we update the documentation to make it easier and more explicit for devs to know how to spy on simple functions (or callables in general) like above, or does it make sense to try to implement something like `mocker.patch("src.some_utils.sum_x_y", side_effect=MagicMock(wraps=sum_x_y))` (including `AsyncMock`) ?

Thanks for your time!

**Comment by nicoddemus** [comment]
Hi @mromagnoli,

Thanks for writing. 

> Should we update the documentation to make it easier and more explicit for devs to know how to spy on simple functions (or callables in general) like above

I prefer just updating the docs, I personally not a big fan of the `mocker.patch("module as string")` interface, so I prefer to keep `spy` signature as is. 😁

**Comment by nicoddemus** [comment]
Added an example, thanks again!
