### ISSUE TITLE
Add mocker.resetall()

### ISSUE THREAD

**Issue by mathrick** [pytest-dev/pytest-mock#23]
Having a `mocker.resetall()` method, similar to `mocker.stopall()`, would be very handy. Most of the time if I mock things, it's because I'm testing a side-effecting function which cannot be blackboxed effectively, and will want to walk through multiple code paths while checking that various callees were/were not called as appropriate. This commonly involves resetting the mocks, so not having to reset them individually would greatly increase the usefulness of `mocker`.

**Comment by nicoddemus** [comment]
Thanks for the feedback @mathrick. I'll try to get to this ASAP, but meanwhile a PR would be welcome. :smile:

**Comment by mathrick** [comment]
I gave it a shot, but it turns out to be more complex than `stopall()`, since unlike `.stop()`, `.reset_mock()` isn't defined on the `mock._patch` class, and the multiple levels of indirection are a pain to figure out. So for now I consider myself defeated.
