### ISSUE TITLE
Since 3.3.0 github is missing releases confusing users

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-mock#245]
When you visit https://github.com/pytest-dev/pytest-mock you only see version 3.3.0 as latest. Even if you click releases page you still see the same.

While after while you may be lucky to discover that tags for newer versions exists, that does not provide the best experience.

Ideally github releases should be created for any releases, so they are displayed correctly. If, for some reason, the project maintainers do not want to make releases using github, at least it should remove the releases tab from the project as it is really confusing.

I personally use github releases to make releases and never push tags, but I think it may be possible to use an action that creates a release when a tag is pushed, i just never did it. Somehow I find the web interface better for performing releases,.

**Comment by nicoddemus** [comment]
Hi @ssbarnea,

Thanks for bringing this up! I completely forgot lately about doing GH releases lately. 

I have created releases for the missing tags, thanks for the reminder.

> I personally use github releases to make releases and never push tags, but I think it may be possible to use an action that creates a release when a tag is pushed, i just never did it.

I wrote one for pytest: https://github.com/pytest-dev/pytest/blob/main/scripts/publish-gh-release-notes.py. I intended to make that into a standalone package, but never got around to do it.

Thanks again!
