### ISSUE TITLE
Patch methods should return AsyncMock if the target is an async method

### ISSUE THREAD

**Issue by GDYendell** [pytest-dev/pytest-mock#254]
This would match the behaviour of the equivalent methods in [`mock`](https://github.com/python/cpython/blob/main/Lib/unittest/mock.py#L1687)

Currently, I can pass `new_callable=AsyncMock` to make it work, but then mypy type checking fails because the type hints state that the methods return `MagicMock`. The return type is a union in the [mock stubs](https://github.com/python/typeshed/blob/master/stubs/mock/mock.pyi#L170).

**Comment by nicoddemus** [comment]
Hi @GDYendell, thanks for bringing this to attention.

**Comment by nicoddemus** [comment]
Hi @GDYendell,

There's a PR for this in #364, but I wonder if you could post an example of a `mypy` failure? See my comments in https://github.com/pytest-dev/pytest-mock/pull/364#discussion_r1223710450.

**Comment by GDYendell** [comment]
Hi @nicoddemus 

This was a while ago now so I doing some digging trying to remember. There is a chain of issues that leads to https://github.com/testing-cabal/mock/issues/500 where I included a mypy error.

The repo this was happening is https://github.com/dls-controls/odinprocservcontrol. I have created a `mypy` branch from an old commit to recreate the problem [here](https://github.com/dls-controls/odinprocservcontrol/actions/runs/5219900027/jobs/9422288095#step:6:60). It [works](https://github.com/dls-controls/odinprocservcontrol/actions/runs/5219807227/jobs/9422082840#step:6:87) on master with the [updated](https://github.com/dls-controls/odinprocservcontrol/commit/6056b44c96b0f946ebb07039e096782a888f8798) `types-mock`. If it is useful to recreate the problem locally, checkout the `mypy` branch and do a `pipenv install --dev --ignore-pipfile` and run `pipenv run mypy tests`.

I have briefly looked through #364, but don't immediately understand the detail of the change - is this useful information? Let me know if there is anything else I can do to help.
