### ISSUE TITLE
Allow patching methods by reference

### ISSUE THREAD

**Issue by ikonst** [pytest-dev/pytest-mock#261]
In our codebase's unit tests we often mock out dependencies by patching individual methods of instances, i.e.
```python
def test_something(mocker: MockerFixture):
   mocker.patch.object(foo_client, 'get_bar', return_value=42)
   ...
```
Other times we patch them on the class level, which has the advantage of not needing access to a particular instance:
```python
def test_something(mocker: MockerFixture):
   mocker.patch.object(FooClient, 'get_bar', return_value=42)
   ...
```

It always rubbed me the wrong way how the 2nd argument to this `patch.object` is "stringly typed". This prevents our IDE from being aware of the mocking when refactoring, and precludes the conveniences of symbolic code navigation ("go to definition", "find references").

Here's an experimental addition I've made in our code base:
https://gist.github.com/ikonst/cc28e815008c6487af91a10e3a1fdd7a

For bounded methods, converting a method reference to (instance, name) is very easy. For unbounded methods, a rather hacky approach is required, but I believe it's reasonable for test code and the benefits outweigh the hackiness :)

**Comment by nicoddemus** [comment]
Hi @ikonst,

I emphasize with the idea (and like it too), however you will notice the signature of `mocker.patch.object` is the same as `unittest.mock.patch` intentionally, and I would prefer to avoid deviating from it.

Perhaps we can add new methods though? `mocker.patch.method` and `mocker.patch.function`?

**Comment by ikonst** [comment]
patch.method is exactly what it's called in my gist :)

**Comment by ikonst** [comment]
Suddenly this feels way too complex. For one, it misses the other obvious use cases:
```python
patch.function(my_module.my_func, ...)
patch.function(tested_module.my_func, ...)
patch.function(tested_module.my_func_imported_under_different_name, ...)
```

Some thoughts:
1. What I'm doing for class methods is a special case of doing `gc.get_referrers` and patching all referrers. What if we provided an easy way to do just that, rather than special-casing class methods, instance methods and functions?
2. If my goal is to replace what a function does, why not overwrite its `__code__` property and then revert it at the end of the patch?

Notably both of those approaches would be patching that's agnostic to the import location (i.e. it'll apply to all imports). I've yet to test those approaches on some real code, but just wanted to share some thoughts before I have time to tinker.

**Comment by nicoddemus** [comment]
Hmm if implementing the convenience methods is not as simple as we hoped, with the possibility of possibly not working in some corner cases, I'm leaning towards not including this at all: the minor convenience will probably cause more maintenance headaches than it is worth it. 😖

**Comment by ikonst** [comment]
I'm not saying it's more complex. Rather, I'm saying it could be generalized to be simpler and applicable in more cases (e.g. patching a function rather than a method).

(And the convenience is major, at least in the codebases I work in, since it effectively what makes refactoring much harder.)

**Comment by nicoddemus** [comment]
Hmmm I see. 

Well particularly I'm not a big fan of patching `__code__` objects and such to accomplish that, so that approach is a 👎 from me. I the code you linked is a good balance between convenience and code simplicity TBH.

> (And the convenience is major, at least in the codebases I work in, since it effectively what makes refactoring much harder.)

Ahh I see, thanks.

**Comment by ikonst** [comment]
I haven't dug into patching `__code__` yet (just wanted to check viability, I can imagine it being trickier than I'd wish) but just wondering what seems so unsavory to you about this?

From what I've seen 99 times out of 100, the intention is the patching is to "patch out" some code that absolutely cannot run to completion within the test environment (e.g. relying on a network call), no matter what reference it's executed through, rather than to patch out a particular reference, and patching a reference is merely the way to prevent it from being executed. And you must be familiar with the "what reference did you patch?" caveats of doing that.

**Comment by nicoddemus** [comment]
>  just wondering what seems so unsavory to you about this? 

Changing the internal code objects for patching doesn't sit well to me, seems like we are setting up for maintenance problems and hard to debug issues down the line. I could be wrong, but I don't want that for `pytest-mock` as I would be maintaining it long term, hehehe.

**Comment by ikonst** [comment]
OK, I'm starting to realize why patching `__code__` doesn't work.

The `code` itself doesn't reference anything. Binding to an instance and closure variables are a property of a `function`, not `code`. Effectively `SomeClass.some_func.__code is instance.some_func.__code__`.

For example, let's say we take a simple function `f(int)` and "hollow it out"  by replacing its `__code__` with `some_mock.__call__.__code__`: when we call `f(42)` it would pass the 42 as the `self` to `Mock.__call__` -- the fact that `some_mock.__call__` is a bound method is not manifested in the `code` object.

**Comment by ikonst** [comment]
Spent some time today trying out the first approach too.

Here's what a `patch.refs` implementation can look like:
https://github.com/ikonst/pytest-mock-experiments/blob/main/pytest_mock_experiments/plugin.py#L108-L131

Usage example for patching all references to a function:
https://github.com/ikonst/pytest-mock-experiments/blob/b4e0e0d25138dd2f24645fc4cac7d2e9379b41f8/tests/test_mocker.py#L64-L76

Usage example for patching (all references to) an object:
https://github.com/ikonst/pytest-mock-experiments/blob/b4e0e0d25138dd2f24645fc4cac7d2e9379b41f8/tests/test_mocker.py#L46-L57

**Comment by nicoddemus** [comment]
Thanks @ikonst for that.

I see the implementation, it is clever! However to be perfectly honest, I'm going to have to say no to integrating it into `pytest-mock`, as I have a feeling this will bring more maintenance issues than I'm willing to take on, like weird side effects, not working in special cases, etc.

Note that this can be easily implemented as a function which receives `mocker` as an argument, in case you want to use that in your code base without subclassing `MockerFixture`. Another possibility would be to publish your own extension of this plugin and reuse that.

Really sorry you have spent time to implement it and in the end I have to say no, but I need to think about the long term effects this will have in the project, and specially, the maintenance that this might bring my way. The intention for this plugin was always to be a thin wrapper around `unittest.mock`, and it has grown extra functionality which some I'm happy with, and other I regret today, but don't want to remove to avoid breaking users' suites.

Again, thanks for the interest and sharing. 👍

**Comment by ikonst** [comment]
I actually have to agree with you here. I think pytest-mock's place is to be a thin wrapper - extra functionality can be a burden and also can blur the lines of responsibility. Here's what I added recently to pynamodb's contributing section: https://github.com/pynamodb/PynamoDB/blob/master/docs/contributing.rst#the-scope-of-the-library

BTW, I was trying the `patch.refs` approach in a real-world codebase and it's ... tricky. For example, you might really have one particular ref in mind when you're patching, but since it'd patch all refs, it might e.g. fail to patch a ref that's in a frozen dataclass (that you never intended to patch).

**Comment by nicoddemus** [comment]
> I actually have to agree with you here. I think pytest-mock's place is to be a thin wrapper

Thanks for being understanding!

> BTW, I was trying the patch.refs approach in a real-world codebase and it's ... tricky. For example, you might really have one particular ref in mind when you're patching, but since it'd patch all refs, it might e.g. fail to patch a ref that's in a frozen dataclass (that you never intended to patch).

Yeah that's the kind of corner case I was mentioning that I suspected would pop-up. 👍 

Closing this for now then, thanks again!
