### ISSUE TITLE
`mocker.patch.dict` does not match `unittest.mock.patch.dict` behavior

### ISSUE THREAD

**Issue by spagh-eddie** [pytest-dev/pytest-mock#262]
Hello, I cannot seem to get mocker's `patch.dict` to work as the same as unittest's. I would have expected both `test_mocker` and `test_mock` below to pass. 

## MRE
```console
% cat test.py 
def test_mocker(mocker):
	with mocker.patch.dict({}, {}):
		assert 1

def test_mock():
	from unittest import mock
	with mock.patch.dict({}, {}):
		assert 1
```
```console
% pytest test.py
======================== test session starts =========================
platform darwin -- Python 3.7.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/edoyle/Desktop/spagh-eddie/icsw
plugins: doctest-ellipsis-markers-0.1.0, mock-3.6.1
collected 2 items                                                    

test.py F.                                                     [100%]

============================== FAILURES ==============================
____________________________ test_mocker _____________________________

mocker = <pytest_mock.plugin.MockerFixture object at 0x104de96d0>

    def test_mocker(mocker):
>   	with mocker.patch.dict({}, {}):
E    AttributeError: __enter__

test.py:2: AttributeError
====================== short test summary info =======================
FAILED test.py::test_mocker - AttributeError: __enter__
==================== 1 failed, 1 passed in 0.09s =====================
```

**Comment by nicoddemus** [comment]
Hi @spagh-eddie,

`mocker` is not supposed to be used as a context manager, please see:

https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager

https://github.com/pytest-dev/pytest-mock#why-bother-with-a-plugin

**Comment by pviolette3** [comment]
Hi, thank you for this great tool!

> mocker is not supposed to be used as a context manager:
I was wondering if we can mention this information in the official docs.

The [official docs](https://pytest-mock.readthedocs.io/en/latest/usage.html#usage) link to the standard library mocking library for `mocker.patch.dict`; however, I am still reproducing broken context manager behavior from this ticket.

Wondering if you can advise.

**Comment by nicoddemus** [comment]
> I am still reproducing broken context manager behavior from this ticket.

The idea of the `mocker` fixture is t *not* use it as a context manager, see:

[pytest-dev/pytest-mock#note-about-usage-as-context-manager](https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager)
