### ISSUE TITLE
Patch.multiple not behaving exactly like unnitest implementation

### ISSUE THREAD

**Issue by ledermauss** [pytest-dev/pytest-mock#271]
I have a class where I am trying to mock multiple methods (but not all) using `mock.patch.multiple`. The class goes like this (inside a module named `module`):

```
class MyClass:
     method1(self):...
     method2(self):...
```

And here is the mocking part. I am using the `pytest-mocking` package.
```
from package import module as m
from pytest_mock import MockFixture

@pytest.fixture
def mocked_methods(mocker: MockFixture) -> Dict:[str, MagicMock]:
    return mocker.patch.multiple(m.MyClass, method1=Default, method2=Default)
```
This fixture is always empty. However, if I instead use the original, `unittest` API, it works as expected:

```
from unittest.mock import patch
...
with patch.multiple(m.MyClass, method1=DEFAULT, method2=DEFAUL) as patched:
    asssert isinstance(patched["method1].side_effect, MagicMock) is True
```
The code below always works. However, the `mocker.patch.multiple` returns None (an empty dictionary actually). Why is this happening?

**Comment by nicoddemus** [comment]
Hi @ledermauss,

Thanks for writing.

Not sure why `mocker.patch.multiple` is returning an empty dict. We have tests in place for `mocker.patch.multiple`, and they work as expected (we get a dictionary with the mocks).

Could you provide a reproducible example for me to investigate?

**Comment by ledermauss** [comment]
Hi @nicoddemus,

thanks for your reply.

I could fix the issue! I figured out what was happening, although I do not understand what was wrong.

I had `mock_use_standalone_modules` set to `true` on my `pytest.ini` file. After removing that, it works. Why? I thought this would "use a newest version of the mock package as published on PyPI than the one that comes with the Python distribution". FYI, here is what my .venv contains:

- mock: 4.0.3
- pytest: 6.2.3
- pytest-mock: 3.6.1

Which I used with this imports:
```
from unittest.mock import MagicMock, DEFAULT, patch
import pytest
from pytest_mock import MockFixture
```

Maybe a conflict with unittest.mock?

**Comment by nicoddemus** [comment]
Thanks for investigating! Closing then as it doesn't seem an issue with `pytest-mock`.

> I thought this would "use a newest version of the mock package as published on PyPI than the one that comes with the Python distribution"

It means it will import `mock` instead of `unittest.mock`, which may or may not be the latest version on PyPI.

> Maybe a conflict with unittest.mock?

Not sure. 😕 This would require to debug the call into `mock.patch.multiple`, but I'm short on time to delve into it.

Thanks again!
