### ISSUE TITLE
Am I using stub properly for testing with http call?

### ISSUE THREAD

**Issue by Taewa** [pytest-dev/pytest-mock#281]
Hi all, 
I am new to Python and pytest-mock.
Basically, I am not sure what I am trying is correct approach and understanding properly.

```py
# test_some_func.py

import pytest
import pytest_mock
from my_project import Some_func
from my_project.utils import some_request

class TestClass:
    def test_some_func(self, mocker: pytest_mock.MockFixture):
        some_func = Some_func()
        mock_some_request = mocker.stub('my_project.utils.some_request') # trying to stub the function and prevent http call

        some_func.func_x()

        mock_some_request.assert_called()

```

```py
# some_func.py

from my_project.utils import some_request

class Some_func:
    def func_x(): 
        some_request()
```

```py
# utils.py

import requests

def some_request():
    return requests.get(...)

```

My intention of the test is that whether `some_request` is being called or not when `func_x` is executed.
I expect that the `stub` will replace the real `some_request` method and verify if it's called. But I keep getting 
`AssertionError: Expected 'my_project.utils.some_request' to have been called.`

I could find only one example of stub which from the readme file. Can you please guide me what am I doing wrong?

////// EDIT //////
I tried with `patch`.
```py
# test_some_func.py

import pytest
import pytest_mock
from my_project import Some_func
from my_project.utils import some_request

class TestClass:
    def test_some_func(self, mocker: pytest_mock.MockFixture):
        some_func = Some_func()
        mocker.patch('my_project.utils.some_request', return_value=1) # replace with patch
        actual = some_func.func_x()

        assert 1 == actual

```

I expected the `actual` should be `1` because I get it `return_value=1` but it returns a `dict`. And getting `Unverified HTTPS request is being made to host 'localhost'.` warning message which implies http call happened.

**Comment by nicoddemus** [comment]
You are right, you should use `patch`, `stub` only gives you a MagicMock object that can be used for other things, like passing to a function and see how it was used.

As for the last problem, you need to change how you import `some_request` in `utils.py`:

```python
class Some_func:
    def func_x(): 
        from my_project.utils import some_request
        some_request()
```

or:

```python
from my_project import utils 

class Some_func:
    def func_x(): 
        utils.some_request()
```

See https://docs.python.org/3/library/unittest.mock.html#where-to-patch for more information.

Closing for now, feel free to follow up with further questions.
