### ISSUE TITLE
Format of message "Use -v to get..." has changed in pytest 7.1.0 breaking some pytest-mock tests

### ISSUE THREAD

**Issue by juliangilbey** [pytest-dev/pytest-mock#293]
In commit https://github.com/pytest-dev/pytest/commit/fac8f284cd6ffd44c7d401093c67799766473be1 the message returned from `_pytest.assertion.util._compare_eq_iterable` changed from `Use -v to get the full diff` to `Use -v to get more diff`, which breaks two of the tests in this plugin that have the message hard-coded (`test_detailed_introspection` and `test_detailed_introspection_async`).  Suggestion: change the comparison string to `"*Use -v to get*"`.

**Comment by nicoddemus** [comment]
Hi @juliangilbey,

Thanks for the report.

This is however fixed in `main` already by 0577f1ad051fb8d0da94ea22dcb02346d74064b2. 👍

**Comment by juliangilbey** [comment]
Ah, great, sorry for the noise then!

**Comment by nicoddemus** [comment]
No worries, thanks again!
