### ISSUE TITLE
can't capture stderr from external process

### ISSUE THREAD

**Issue by ynikitenko** [pytest-dev/pytest-mock#295]
I write an `rsync` wrapper in Python. When I test for error messages, I can capture `stderr` from my program (because it uses Python `sys.stderr`), but `rsync` error messages are not captured. Is it a bug, or what should I do differently? Here is my code:

    def test_status_error_bad_permissions(mocker, test_dir_ys_bad_permissions):
        os.chdir(test_dir_ys_bad_permissions)
        mocker_stderr = mocker.patch("sys.stderr")
        ys = YARsync(["yarsync", "status"])
        returncode = ys()
        written_stderr = "".join(call[0][0] for call in
                                 mocker_stderr.write.call_args_list)
        assert 'test_dir_ys_bad_permissions/forbidden" failed: Permission denied '\
             in written_stderr
        # fails: written_stderr is ''

A very same code works when I capture my Python stderr in another function (here is a link to the [complete test file](https://github.com/ynikitenko/yarsync/blob/11dd4d0acc939b2f0e3a345becb4812148601a51/tests/test_status.py), you can clone the repository and test it yourself).

I found a note in `pytest` documentation, which states that there are [several levels of error capturing](https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html#setting-capturing-methods-or-disabling-capturing): file descriptor (default), `sys` level and both. And `pytest` indeed captures these `stderr` calls. Is there a way to capture them in `pytest-mock`?

I also tried to `patch.object(sys.stderr, "write")`, but it made no difference.

**Comment by ynikitenko** [comment]
I use Arch Linux, Python 3.10.5 and pytest-mock 3.6.1.

**Comment by nicoddemus** [comment]
Mocking (be it `mock`, `pytest-mock`, `monkeypatch`) won't affect other processes, as it operates on the Python level by replacing the actual attributes with their mock counterparts.

If pytest is capturing it, you can use the [capfd fixture](https://docs.pytest.org/en/stable/reference/reference.html#capfd) to capture the output in the test and check it.

Closing for now, feel free to follow up with further questions!

**Comment by ynikitenko** [comment]
Many thanks, this works! Not sure whether the more appropriate place for a question was StackOverflow, but I thought this was a bug so I asked here (after I searched for `stderr` in all issues and googled).
