### ISSUE TITLE
TypeError when assert_called_with is used

### ISSUE THREAD

**Issue by sagarchalise** [pytest-dev/pytest-mock#31]
I get an odd behavior during assert_called_with when using mocker.

`TypeError: assert_wrapper() got multiple values for keyword argument`

Also there is no issue when mock itself is used.

**Comment by nicoddemus** [comment]
Oh sorry somehow I missed this issue.

I will investigate, thanks for the report! :smile:

**Comment by nicoddemus** [comment]
Could you post a small reproducible case? Python version as well.

**Comment by sagarchalise** [comment]
@nicoddemus This issue is produced in https://github.com/sagarchalise/picovico-python-sdk/tree/cli-client `py.test -s tests/baserequest_test.py::TestPicovicoRequest::test_api_methods` . 

See: https://github.com/sagarchalise/picovico-python-sdk/blob/cli-client/tests/baserequest_test.py#L35

**Comment by nicoddemus** [comment]
Fixed, thanks! I will release `0.11` shortly. :grin:

**Comment by nicoddemus** [comment]
Released `0.11.0`, thanks!
