### ISSUE TITLE
#note-about-usage-as-context-manager leads to no message

### ISSUE THREAD

**Issue by stdedos** [pytest-dev/pytest-mock#312]
https://github.com/pytest-dev/pytest-mock/blob/35e2dca0ab5e0a0e1580359f7effd6ef99a7c8e6/src/pytest_mock/plugin.py#L212-L220

Leads to the now not-existing section of the README.rst:
https://github.com/pytest-dev/pytest-mock/blob/4c3caaf2260f77ed10e855a20207023dded12c07/README.rst#L277-L315

**Comment by nicoddemus** [comment]
Fixed, thanks!
