### ISSUE TITLE
start, stop and stopall

### ISSUE THREAD

**Issue by LeonardoGentile** [pytest-dev/pytest-mock#315]
Hello, 
I'm having some trouble wrapping my mind around this.

This is my simplified app:
```
# my_package.app
from my_package.logger import log
from my_package.api import call_api

def main():
    try:
        call_api()
    except Exception as e:
        log(e)
```

This is my conftest, where I define my fixtures:

```
# conftest.py
@pytest.fixture(name="mocked_api")
def fixture_mocked_api(mocker):
    """Mocked fn that call  api"""
    mock = mocker.patch('my_package.app.call_api', return_value=None)
    return mock


@pytest.fixture(name="main_fn")
def fixture_main_fn(mocked_api, other_fixture_1, other_fixture_2):
    from my_package.app import main
    
    mocked_api.start()
    export main
 ```

I use `mocked_api` inside the `main_fn` fixture that I mainly uses in all my tests.
Now in a particular test I want to reset the `call_api` ( in the app module) to its original value, so I do this:

```
class TestApp:
    def test_my_app(self, main_fn, other_fixture_1):
        # test something
        pass
    
    def test_my_app_raise(self, main_fn, mocked_api, other_fixture_2):
        mocked_api.stop()
        # ....
        # ....
```

I have probably misinterpreted how to use start/stop and stopall but no matter what, even if I call `mocked_api.stop()` the original `call_api` inside `app` is not restored and the mocked version will be called instead. 

I guess this has to do with the fact that also `main_fn` use the `mocked_api` fixture.
I have though about using `mocked_api.stopall()` but still no luck.

I'm clearly doing something wrong.

How can I reset `app.call_api` to its original value even if the `mocked_api` is used in `main_fn` that is used in `test_my_app_raise`?

**Comment by nicoddemus** [comment]
Hi, 

[`stop()`](https://docs.python.org/3/library/unittest.mock.html#patch-methods-start-and-stop) is a method of a *patch object*, not of the mocked object (which is what is returned from `patch().start()`).

You want to call `mocker.stopall()` (the `mocker` fixture).

Closing, but feel free to follow up with further comments.
