### ISSUE TITLE
GitHub Admin: Add docs to repo links

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest-mock#327]
This is only available to the org admin / owners I believe. You'd have to have settings available

https://pytest-mock.readthedocs.io/en/latest/

Example from https://github.com/pytest-dev/pytest
![image](https://user-images.githubusercontent.com/26336/197355892-55ccc259-aeea-43a2-b642-a4ff7d8cef9f.png)

**Comment by nicoddemus** [comment]
Thanks for the pointer, done!
