### ISSUE TITLE
Feature request: Add Documentation link to config for pypi

### ISSUE THREAD

**Issue by koutoftimer** [pytest-dev/pytest-mock#330]
[Project page on pypi](https://pypi.org/project/pytest-mock/) doesn't have "Documentation" section on the side panel as, e.g. [Django](https://pypi.org/project/Django/) does.

UX can be improved a bit by adding corresponding configuration, similar to [what Django does](https://github.com/django/django/blob/c0a93d39411004300dfda2deb3dc093b69ac6368/setup.cfg#L29-L30)

**Comment by nicoddemus** [comment]
Thanks @koutoftimer, indeed that would be nice. Would you like to submit a PR?

**Comment by koutoftimer** [comment]
@nicoddemus probably. I can't see any dynamic stuff in `setup.py`, so it can be converted to `setup.cfg` and so to `pyproject.toml` (though I'm not a fan of it because of not mature ecosystem around it)

HOWTOs:
* https://www.youtube.com/watch?v=GaWs-LenLYE

**Comment by nicoddemus** [comment]
I think it is just a matter of passing [`project_urls`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls) to `setup()` in `setup.py`, no need to change configuration files.
