### ISSUE TITLE
Discussion: how to "better" type `mocker.patch` return

### ISSUE THREAD

**Issue by staticdev** [pytest-dev/pytest-mock#338]
Let's be some pytest fixture using pytest_mock:

```python
import pytest
from unittest.mock import MagicMock

@pytest.fixture
def mock_something(mocker: MockerFixture) -> MagicMock:
    return mocker.patch("something")
```

Good thing about this code is that code completion works and at runtime my return `isinstance` of MagicMock. What I don't like is that I have a pytest project and ideally with pytest_mock I could not have to import unittest at all.

If instead I do:

```python
import pytest
from pytest_mock import MockerFixture

@pytest.fixture
def mock_something(mocker: MockerFixture) -> MockerFixture:
    return mocker.patch("something")
```

Good is that mypy checks will pass and I do not need to import unittest on a pytest project. Bad thing it is technically not correct, since `MockerFixture` is not instance of `MagicMock` and code completion will not have methods such as `assert_called_once`.

My point is.. can we make this better with current pytest_mock implementation to have best of both? Code completion works, no imports on unittest, static and dynamic types are correct? If not, maybe we can do a change in pytest_mock to make typing abstract completely `unittest.mock`?

@srittau marking you since you did the original type interface on python/typeshed.

**Comment by srittau** [comment]
One easy solution is to just re-export `MagicMock` from `pytest_mock`, although I don't see the issue with import `MagicMock` from `unittest.mock`.

**Comment by nicoddemus** [comment]
> although I don't see the issue with import MagicMock from unittest.mock.

Yeah, note that `pytest-mock` is just a layer on top of `unittest.mock`, so I don't think that importing `unittest.mock` is a problem.
