### ISSUE TITLE
mocker.patch does not change return value

### ISSUE THREAD

**Issue by louis030195** [pytest-dev/pytest-mock#349]
In
https://github.com/different-ai/embedbase/blob/601c4c227993b8c081ddf3eeaddeca66423bd1ca/embedbase/test_end_to_end.py#L334

I'm trying to mock `embedbase.utils.get_user_id` returning `user1` but when calling the function it does return None instead, is there something I did wrong or misunderstood?

```py
mocker.patch("embedbase.utils.get_user_id", return_value="user1")
```

Thanks!

**Comment by nicoddemus** [comment]
Hi,

Did not take a deep look at the code, but probably is the matter of patching in the wrong place, see [Where to patch](https://docs.python.org/3/library/unittest.mock.html#where-to-patch).

**Comment by louis030195** [comment]
I tried to patch on every single lines without better result :/
