### ISSUE TITLE
Mock method don't work when test from other file fail

### ISSUE THREAD

**Issue by LeonardoFurtado** [pytest-dev/pytest-mock#372]
### Context
I wrote a test on a X file that mock a method and this test pass, but when I wrote other test on a Y file and this test failed the test on the X file failed too. I was debugging it and I perceived that the mock o X file did not worked when the test on Y file failed. But this only happen when I use `@pytest.mark.django_db` on the test. 

### How to reproduce
I wrote a small project just to reproduce it: https://github.com/LeonardoFurtado/djangoProjectPytest 
You just need to git pull it, run `pipenv shell` and `pipenv install` to setup the environment and run `pytest`.
After it you will see 2 tests failing.
Go to the `test_a_failed_test.py` file and comment the line `@pytest.mark.django_db`. Now only one test will fail.
This is happening because the mock `create_user` on `conftest.py` now is working after comment it.

This is a simple api:
```python
class ProfileView(APIView):
    def post(self, request):
        auth_context = get_auth_context(1) # expected: 2 but i will mock it as 3
        if auth_context == 2:
            return Response(
                {
                    "success": False,
                    "error": "The get_auth_context is returning the number 2 instead of the mocked value 3.",
                },
                status=status.HTTP_400_BAD_REQUEST,
            )
        elif auth_context == 3:
            return Response(
                {
                    "success": True,
                    "error": "Ok. The get_auth_context is returning the mocked value",
                },
                status=status.HTTP_200_OK,
            )
```

the test below  is the test who pass and use the create_user mock I only pass when the create_user mock works.
```python
@pytest.mark.django_db
def test_create_profile(api_client, create_user):
    data = {
        "name": "Naruto Uzumaki",
    }
    response = api_client.post('/profiles/', data=data)
    assert response.status_code == 200
```

the mock:
```python
@pytest.fixture
def create_user(mocker):
    return mocker.patch("core.auth.get_auth_context", return_value=3)
```

This is the test I created to fail on purpose, when you comment `@pytest.mark.django_db` the other test stops failing for some reason because the mock above starts to work again.
```python
@pytest.mark.django_db
def test_random_test(api_client):
    """
    If you comment this test, the test on file test_auth_context will pass
    """
    response = api_client.patch(
        '/route/that_doesnt_exists/',
        format='json'
    )
    assert response.status_code == 200
```
If you need more details please tell me.

**Comment by nicoddemus** [comment]
Dae @LeonardoFurtado,

pytest-mock is just a thin layer over `unittest.mock`, so I don't think the problem is related to `mocker`.

Please change `create_user` to:

```python
@pytest.fixture
def create_user():   
    with unittest.mock.patch("core.auth.get_auth_context", return_value=3):
        yield
``` 

This will not use the `mocker` fixture at all, just the builtin `unittest.mock`. This will let us know if the problem lies with `pytest-mock` or elsewhere -- probably the mark is causing some other `get_auth_context` to be called or something.

**Comment by LeonardoFurtado** [comment]
> Dae @LeonardoFurtado,
> 
> pytest-mock is just a thin layer over `unittest.mock`, so I don't think the problem is related to `mocker`.
> 
> Please change `create_user` to:
> 
> ```python
> @pytest.fixture
> def create_user():   
>     with unittest.mock.patch("core.auth.get_auth_context", return_value=3):
>         yield
> ```
> 
> This will not use the `mocker` fixture at all, just the builtin `unittest.mock`. This will let us know if the problem lies with `pytest-mock` or elsewhere -- probably the mark is causing some other `get_auth_context` to be called or something.

You're right, I got the same error after make this change

**Comment by nicoddemus** [comment]
Thanks.

I suggested to post your question to `pytest-django` (using the changed `created_user`), they might be able to help you better.

Valeu!

**Comment by LeonardoFurtado** [comment]
> Thanks.
> 
> I suggested to post your question to `pytest-django` (using the changed `created_user`), they might be able to help you better.
> 
> Valeu!

vlws
