### ISSUE TITLE
Record multiple calls to spy

### ISSUE THREAD

**Issue by acroz** [pytest-dev/pytest-mock#378]
Hi, I have a use case where I'd like to use `mocker.spy()` to record all calls to and return values from a callable, however as far as I can tell `mocker.spy()` only records the most recent call (as `spy_return`).

Would you welcome a merge request adding this, and if so, do you have any opinions on the API?

I was thinking of something like `spy_returns` or `spy_return_list`, which would be a list of return values. I'm not sure how best to handle exceptions - put the return values and exceptions in the same list so the user can determine order, or have two lists? Alternatively just assume that if you're expecting an exception there's less likely to be a need to call it multiple times.

**Comment by frank-lenormand** [comment]
Any thoughts on this?

**Comment by nicoddemus** [comment]
Sorry seems I missed this one.

I think `spy_return`/`spy_return_list` mirrors MagicMock's `call_args`/`call_args_list` nicely, so I would go with `spy_return_list` which returns the list of `call` values.

About exceptions, I don't think we have similar support for "list of exceptions" in MagicMock (or even normal exceptions for that matter) to draw from, but keeping consistency with `spy_exception`, seems reasonable we could have a list of `spy_exception_list` too.

However I would not implement `spy_exception_list` right away unless someone presents a use case to track a list of exceptions raised by the spied function.

Having said that, I would love to review a PR which adds `spy_return_list`. 👍
