### ISSUE TITLE
Undo mocks on debugging hooks?

### ISSUE THREAD

**Issue by jtatum** [pytest-dev/pytest-mock#38]
I wrote a series of test cases which patch `builtin.open()` to return a StringIO/BytesIO. pytest-mock handles these well, but when the test fails, pytest's exception handler uses open to print info about source files. PDB is also broken in test cases that patch open(). Errors like the following will occur when trying to use pdb, either directly or via --pdb:

```
ValueError: I/O operation on closed file.
```

pytest has a few hooks related to debugging, including `pytest_enter_pdb` and `pytest_exception_interact` - both seem promising. It would be nice to be able to patch `open()` in a way that would get undone if the test fails and the exception handler is entered.

**Comment by nicoddemus** [comment]
@jtatum,

While I sympathize with your use case, I fear if `pytest-mock` would automatically uninstall all patches when a test fails or pdb is entered then legitimate use cases would no longer be possible. For example, more than once I used pdb to trace a function that was used to replace another using mock. If `pytest-mock` would automatically undo all patches when entering pdb, I would now trace into the real function, which is certainly unexpected and surprising.

IMHO your use case is very specific to the `open` builtin, which is indeed a sensitive function to mock (as I'm sure other builtins would be, for example `str`), so I think it makes sense to code something specific to your test suite: thanks to pytest's flexibility you can easily write the hooks yourself into a `conftest.py` file. Here's something you could do (untested):

```python
import pytest

_mocker = None

@pytest.fixture(autouse=True)
def hold_mocker(mocker):
    # ugly hack to access mocker from other hooks
    global _mocker
    _mocker = mocker
    
def pytest_exception_interact():
    if _mocker:
        _mocker.stopall() 

def pytest_enter_pdb():
    if _mocker:
        _mocker.stopall() 
```

Hope that helps!

**Comment by jtatum** [comment]
@nicoddemus - thank you so much for the sample code! Looks excellent, I'll have to give it a shot later. You're right that having all patches stop on exceptions/pdb is probably undesirable. It would make debugging in many cases much more confusing. I wasn't suggesting that this happen with all patches, just the sensitive ones. Proposed api:

```python
def test(mocker):
    mocker.patch('__builtin__.open', undo_on_debug=True)
    [...]
```

I could work up a PR if something like this makes sense.

**Comment by nicoddemus** [comment]
Hi @jtatum, I'm not really comfortable adding extra parameters to `mocker.patch` TBH. I rather keep the same signature as the original `mock.patch` function.

**Comment by jtatum** [comment]
All right. If there are no code changes desired, might as well close this issue, then.

**Comment by nicoddemus** [comment]
OK, thanks!
