### ISSUE TITLE
The documentation should be clearer about not supporting context managers

### ISSUE THREAD

**Issue by nedbat** [pytest-dev/pytest-mock#382]
This page (https://pytest-mock.readthedocs.io/en/latest/usage.html) simply says, "they all work the same as unittest.mock".  It's not until another page that it says, "except you can't use them as context managers."   The surprising exception should be mentioned on this page.

**Comment by nicoddemus** [comment]
You are right, in fact we did get some reports about this problem. Thanks for bringing it to attention.
