### ISSUE TITLE
Not sure why this is not working

### ISSUE THREAD

**Issue by jiz17043** [pytest-dev/pytest-mock#386]
![image](https://github.com/pytest-dev/pytest-mock/assets/44070470/0f514a48-fdbb-462a-9bbf-c61747a1b46b)
![image](https://github.com/pytest-dev/pytest-mock/assets/44070470/ad059f8e-5a0c-4d10-80db-0c23bd212452)
Try to mock the response of the function in the httprequest_gecko module but it seems not working. Please let me know if you have any suggestions. Thank you!
I am using the latest versions of pytest (7.1.2) and pytest-mock (3.11.1) on Python 3.9.2.

**Comment by The-Compiler** [comment]
Not sure off hand what the issue is, but looks like you're not even using pytest-mock in that screenshot - so this isn't an issue with the plugin.

**Comment by jiz17043** [comment]
I would like to ask for any suggestions if I want to mock a function.

**Comment by nicoddemus** [comment]
@jiz17043 see this section in the docs, as it is likely relevant:

https://docs.python.org/3/library/unittest.mock.html#where-to-patch
