### ISSUE TITLE
[3.13.0] New logged calls in MagicMock mock_calls attribute

### ISSUE THREAD

**Issue by ofx53** [pytest-dev/pytest-mock#420]
Hi! 
Just had some tests fail from which I was looking through mock.mock_calls. Have no seen this documented in the [changelogs](https://pytest-mock.readthedocs.io/en/latest/changelog.html).

![image (3)](https://github.com/pytest-dev/pytest-mock/assets/55769808/28b1714b-2cb6-4a18-b8ff-5b4dea20f231)

![image](https://github.com/pytest-dev/pytest-mock/assets/55769808/17313cc2-19b4-4332-accb-333ad2001e85)

Was this an intended change?

FYI I have found a workaround for the project's tests, just wanted to notify the repo here directly.

Thanks!
Xavier

**Comment by kkroening** [comment]
I ran into a possibly related issue that happens in 3.13.0 but not 3.12.0: `mocker.patch.object` doesn't seem to fully reset between tests, leading to patches bleeding into unrelated tests AFAICT.

**Comment by nicoddemus** [comment]
Hmm seems like an unintended regression.

I have not been able to reproduce the issue however. Any chance of someone providing a MWE? I would be happy to fix it then and make a new release.

**Comment by kkroening** [comment]
Here's an isolated example:
```python
class Class1:
    @staticmethod
    def get():
        return 1


class Class2:
    @staticmethod
    def get():
        return 2


def test1(mocker):
    def handle_get():
        return 3

    mocker.patch.object(Class1, "get", handle_get)
    mocker.patch.object(Class2, "get", handle_get)


def test2():
    assert Class2.get() == 2
```

```bash
python -m venv venv
venv/bin/activate
pip install pytest==8.1.1 pytest-mock==3.13.0
pytest
```

Output:
```
    def test2():
>       assert Class2.get() == 2
E       assert 3 == 2
E        +  where 3 = <function test1.<locals>.handle_get at 0x101950900>()
E        +    where <function test1.<locals>.handle_get at 0x101950900> = Class2.get

test_thing.py:22: AssertionError
```

It fails intermittently, so you may need to run it a few times to reproduce the issue. Oddly enough, it only seems to happen when doing _two_ patches: if you try commenting out either patch in the first test, then the test seems to succeed 100% of the time. Very strange.

(Python 3.11.4)

**Comment by nicoddemus** [comment]
Thanks @kkroening!

I suspected the cause of the problem, but was not able to reproduce because it was working when installed in normal methods, but using staticmethod triggered the problem!

I will make a new release shortly. 👍

**Comment by rkechols** [comment]
I've also run into a problem with `pytest-mock==3.13.0`

Using kkroening's minimal example, this env runs into the bug:
```bash
$ python --version
Python 3.10.13
$ pip freeze | grep pytest
pytest==7.4.4
pytest-base-url==2.1.0
pytest-cov==3.0.0
pytest-mock==3.13.0
```

This environment works fine on the given example:
```bash
$ python --version
Python 3.10.13
$ pip freeze | grep pytest
pytest==7.4.4
pytest-base-url==2.1.0
pytest-cov==3.0.0
pytest-mock==3.12.0
```

For anyone looking for a temporary fix until the new release is out, just to add `,!=3.13.0` to your version specifier of `pytest-mock`, something like `pytest-mock~=3.12,!=3.13.0` or `pytest-mock = "^3.12.0,!=3.13.0"` depending on your packaging tool

@nicoddemus it'd be good if `3.13.0` were also yanked from PyPI

**Comment by nicoddemus** [comment]
> @nicoddemus it'd be good if 3.13.0 were also yanked from PyPI

In general I understand, but we recently yanked pytest from PyPI and the result was not good, it breaks some workflows (which IMO are not correct anyway, but still).

I'm preparing a new release right now.

**Comment by nicoddemus** [comment]
Release 3.14 is out, thanks everyone for the help, and sorry for the regression!
