### ISSUE TITLE
Can you make the license on this MIT?

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest-mock#45]
I can't use any form of GPL at work (including LGPL).  Even if it was possible, the handling considerations wouldn't be worth it for a plugin.  A few months ago I had a remote worker try to borrow code from an LGPL plugin for a project, thinking "hey it's open source, and freedom". Its not easy to convey the ramification of creating a derivative work.

pytest itself is MIT.

**Comment by schollii** [comment]
On May 24, 2016 06:39, "Tony Narlock" <notifications@github.com> wrote:
>
> I can't use any form of GPL at work (including LGPL). Even if it was
possible, the handling considerations wouldn't be worth it for a plugin. A
few months ago I had a remote worker try to borrow code from an LGPL plugin
for a project, thinking "hey it's open source, and freedom". Its not easy
to convey the ramification of creating a derivative work.
>
> pytest itself is MIT.

This only matters if you want to distribute your library and it is packaged
with the plugin, is it your case?
Oliver

**Comment by The-Compiler** [comment]
Note this would probably also require the consent of all contributors as far as I know - while that's probably doable with 13 people, it's still somewhat of a hassle.

**Comment by nicoddemus** [comment]
Myself in my newest projects have followed pytest's example and use MIT, so personally I wouldn't mind. But @The-Compiler is right of course, we should ask consent for all contributors. Perhaps a poll on this thread is enough to obtain consent from everyone? What do you guys think?

**Comment by tony** [comment]
I think the quotation of the email above is broken.

> This only matters if you want to distribute your library and it is packaged
with the plugin, is it your case?

I could go expound on this if you like. I think the onus should rest upon the one backing the more sophisticated license to justify it. GPL is not backward compatible unfortunately.

> Note this would probably also require the consent of all contributors as far as I know - while that's probably doable with 13 people, it's still somewhat of a hassle.

I think the earlier its done the better. As a stop-gap, you can also add to the README that after *this git ref* all future commits are licensed MIT.

**Comment by The-Compiler** [comment]
@nicoddemus As far as I know, other projects handled this by mentioning all people in an issue (like this one) and asking them to respond if they agree with adopting the new license. Should I do so?

@tony With all due respect, if you want to change the license of a project people work on in their free time, it's your job to explain the rationale behind doing so, and not the other way around. :smile: 

FWIW to tick that one off, I'm okay with relicensing my contribution (deleting a file, heh) under the MIT license.

**Comment by nicoddemus** [comment]
> As far as I know, other projects handled this by mentioning all people in an issue (like this one) and asking them to respond if they agree with adopting the new license. 

That's exactly what I had in mind, sorry for not being clearer. :grin: 

> Should I do so?

Yes, thanks! I was planning on doing this tonight, but if you got some minutes to spare I would appreciate it. :smile:

**Comment by tony** [comment]
>  project people work on in their free time,

I think the biggest piece of gratitude you can get (other than money) is that someone using your software. I spent the past few days converting projects from unittest to py.test and apparently am quite happy https://github.com/jonathanslenders/pyvim/pull/35#issuecomment-220822368

> With all due respect, if you want to change the license of a project people work on in their free time, it's your job to explain the rationale behind doing so, and not the other way around. 😄

I offered to elaborate. :smile:

I have before: https://github.com/ScottDuckworth/python-anyvcs/issues/32, https://github.com/urwid/urwid/issues/41, https://github.com/django-wiki/django-wiki/issues/454, https://github.com/Valloric/ycmd/issues/139, https://github.com/pypa/pip/issues/3441, https://github.com/jgm/peg-markdown/issues/35, https://github.com/saitoha/canossa/issues/1

Various outcomes.

**Comment by nicoddemus** [comment]
Thanks for the links, interesting reading. :grin:

**Comment by nicoddemus** [comment]
Here's the list of [contributors](https://github.com/pytest-dev/pytest-mock/graphs/contributors):

- [ ] @fogo 
- [ ] @jurko-gospodnetic
- [ ] @asfaltboy
- [ ] @tigarmo
- [ ] @satyrius
- [ ] @Chronial
- [X] @The-Compiler
- [ ] @rouge8
- [ ] @jespino
- [ ] @RonnyPfannschmidt
- [ ] @jayvdb
- [ ] @blueyed
- [ ] @marcwebbie

**Guys** does any of don't agree to change `pytest-mock` license from [GPL3](http://choosealicense.com/licenses/gpl-3.0/) to [MIT](http://choosealicense.com/licenses/mit/) in the next release?

**Comment by Chronial** [comment]
Fine by me.

**Comment by jespino** [comment]
My contribution in this project is really small (a typo fix), so of course, I agree with the change :smiley:

**Comment by tigarmo** [comment]
You have my permission too, of course!

Tiago

**Comment by fogo** [comment]
MIT license, here we go!

**Comment by RonnyPfannschmidt** [comment]
fine by me

**Comment by blueyed** [comment]
Fine by me!

**Comment by asfaltboy** [comment]
me too, no problemo

**Comment by nicoddemus** [comment]
OK, thanks everyone!

I will change `pytest-mock` license to MIT in the **1.1** release, making sure to mention that prominently on the CHANGELOG.

**Comment by The-Compiler** [comment]
I'd recommend changing the license in the repo ASAP, to make sure new contributors are aware of what license they're licensing their contributions under (in case there should be new people  between now and 1.1).

**Comment by nicoddemus** [comment]
Oh thanks, good point, I will do that later.
