### ISSUE TITLE
.context_manager() only works for object mocking

### ISSUE THREAD

**Issue by eugenenelou** [pytest-dev/pytest-mock#462]
There should be both `mocker.patch.context_manager` and `mocker.patch.object_context_manager`.

**Comment by nicoddemus** [comment]
Thanks @eugenenelou. PRs are welcome!

**Comment by eugenenelou** [comment]
I can do one, but my naming proposal would be a breaking change, maybe you want another?

**Comment by nicoddemus** [comment]
Hmm yeah, you are right. In that case I'm not sure it is worth doing, as one can always just use `unittest.mock` then.

Closing for now, feel free to follow up though.
