### ISSUE TITLE
Provide `mocker.call` name

### ISSUE THREAD

**Issue by jhermann** [pytest-dev/pytest-mock#48]
In order to use the `assert_has_calls` check, you need the `call` name. I think it should be part of the set of 'convenience' names available via `mocker`.

The end goal is to make this work::

    get_pwd = mocker.patch('keyring.get_password')
    …
    get_pwd.assert_has_calls(
        mocker.call(Credentials.KEYRING_SERVICE_DEFAULT, 'jane@keyring.example.com'),
        mocker.call(Credentials.KEYRING_SERVICE_DEFAULT, 'keyring.example.com'))

If you agree it should be available, I can do a PR.

**Comment by nicoddemus** [comment]
Sure, sounds good. A PR would be appreciated! :grin: 

Just a heads up before you contribute: the license for the new yet to be released version is now MIT (#45).
