### ISSUE TITLE
Helper to assert (complete) list of calls in any order?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-mock#51]
With [assert_has_calls](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_has_calls) there's no method to ensure that the list is the complete list of calls: it will only check if the expected list is in the list of calls.

This can be combined with `call_count` then:

    from unittest.mock import call

    expected_calls = [call(1), call(2)]
    mock.assert_has_calls(expected_calls, any_order=True)
    assert mock.call_count == len(expected_calls)

This could be shortened to e.g.

    mock.assert_calls(expected_calls, any_order=True)

`any_order` might default to `True` for this wrapper then even:

    mock.assert_calls(expected_calls)

btw: while there is [mock_calls](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.mock_calls), it does not have the `any_order=True` feature, and
`call` / `_Call` are not hashable and cannot be sorted.

On the other hand, it might be simpler to just use `assert_any_call` multiple times (for each call), and then assert `call_count`, too. This makes it easier to see what call is missing (where the diff might be hard to read):

    mock.assert_any_call(1)
    mock.assert_any_call(2)
    assert mock.call_count == 2

So there's probably not enough reason for adding this to pytest-mock, and if so, it should be (proposed to get) added to `unittest` directly then?

**Comment by nicoddemus** [comment]
> So there's probably not enough reason for adding this to pytest-mock, and if so, it should be (proposed to get) added to unittest directly then?

I think so, I don't want `pytest-mock` to grow its own set of "assert helpers". I think most of them are not needed because thanks to pytest's assertion rewriting you can write the assert yourself and still obtain meaningful messages:

```python
# equivalent to m.assert_calls(expected_calls)
assert m.mock_calls == expected_calls  
```

Plus I'm sure it would confuse users: it wouldn't be clear if a `assert_` method is implemented by `mock` or `pytest-mock`.

But I understand `any_order` is not trivial to implement as well.

**Comment by blueyed** [comment]
Ok, closing this issue here then for now.

**Comment by nicoddemus** [comment]
Thanks!
