### ISSUE TITLE
How to use this with a class of tests?

### ISSUE THREAD

**Issue by ravishivt** [pytest-dev/pytest-mock#52]
I'm new to this library.  I'm using a class of tests with a setUp method.  When I try add mocker as a parameter to a test method, I get `TypeError: test_solution_draft_update_modified_admin() takes exactly 2 arguments (1 given)`.  What's the best way to use the mocker in a class of tests?

```
class ViewTests(APITestCase):
    def setUp(self):
        # do set up

    def test_view(self, mocker):
        # test logic
```

**Comment by nicoddemus** [comment]
I suppose `APITestCase` subclass `unittest.TestCase` right?

Unfortunately you can't have test methods receive fixture parameters in `unittest.TestCase` subclasses because test methods in xUnit are supposed to receive only `self`. 

You can read more about this [here](https://pytest.org/latest/unittest.html#autouse-fixtures-and-accessing-other-fixtures), specially the note at the end.

Hope that helps.

**Comment by ravishivt** [comment]
Thanks @nicoddemus.  Looks like I'm stuck with decorators or the with syntax.

**Comment by mikenerone** [comment]
@ravishivt Sorry for the late reply.

It sounds like you're trying to use pytest the same way you use unittest/xUnit. While there is some attempt at compatibility, what you showed isn't really the "pytest way" of doing that. If I'm understanding you correctly, you were just trying to have a mock put in place for every test in the class. In unittest, you might do that in `setUp()`. The equivalent using pytest and pytest-mock would be something like:

```
class ViewTests:  # No need to inherit anything from unittest. pytest doesn't work that way, this is just a namespace.

    @pytest.fixture(autouse=True)  # pytest will auto-run this fixture for every test in this class.
    def mock_some_func(self, mocker):  # Name is arbitrary, it's the decorator that's important.
        mocker.patch('some.func')  # pytest-mock's auto-teardown will still happen, as well.

    def test_view(self):  # No need to explicitly reference the fixture because of the autouse=True.
        # do something
        some.func.assert_called_once_with(...)
```

Note 1: You can have as many of these autouse fixtures as you like. You _could_ make just one that sets up a bunch of things, or you could separate them out for organization purposes. That's a style thing that's up to you.

Note 2: Alternatively, you could leave off the `autouse=True` and include the fixture name in the test arguments instead. In that case, it will only run for the tests where you do that.

**Comment by nicoddemus** [comment]
Note: autouse also works for unittest.TestCase subclasses. :grin:
