### ISSUE TITLE
Error for Python 3.6 nightly

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pytest-mock#59]
Hi,

our [cookiecutter build](https://travis-ci.org/audreyr/cookiecutter/jobs/149489032) breaks for Python 3.6 nightly due to some error in **pytest-mock**.

```
    class MockFixture(object):
TypeError: '_SentinelObject' object is not callable
```

Figured I'll raise this here although it's certainly not a problem at this point as Python 3.6 isn't out just yet.

**Comment by nicoddemus** [comment]
Thanks! :+1:

**Comment by hackebrot** [comment]
Always 😄

**Comment by mikenerone** [comment]
Though 3.6 is still alpha, I'd like to add a "pretty please." Many projects are wanting to prep for it, and "py36" is being added to tox.ini's everywhere. :)

**Comment by nicoddemus** [comment]
Thanks for the ping! I will take a look ASAP. We should have a release soon anyway, this would be another nice addition. :grin:
