### ISSUE TITLE
Add mock_open feature

### ISSUE THREAD

**Issue by pokidovea** [pytest-dev/pytest-mock#65]
https://docs.python.org/3/library/unittest.mock.html#mock-open

**Comment by nicoddemus** [comment]
Sure, sounds reasonable. Perhaps you can contribute a PR? It should be simple, for example #56 added `sentinel`.

**Comment by pokidovea** [comment]
#66

**Comment by nicoddemus** [comment]
Fixed by #66 

Thanks again!

**Comment by pokidovea** [comment]
no problem
