### ISSUE TITLE
Alias _Call class?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-mock#71]
I am/was using code like the following to detect if some object is a `_Call` instance (to stop recursion in this case):

```python
    from pytest_mock import mock_module

    try:
        _Call = mock_module.mock._Call
    except AttributeError:
        # unittest.mock
        _Call = mock_module._Call
    if isinstance(exp, _Call):
        ...
```

Since `mock_module` has been moved in https://github.com/pytest-dev/pytest-mock/commit/a4cfee7a0843a07e86a458a6c129893356c6b122, I wonder what is the best way to fix / address this.

**Comment by blueyed** [comment]
As you can use `mocker._mock_module` (when the fixture is available), this is OK for me currently.

Feel free to re-open it, if you disagree.. :)

(Previously I was using this without using the `mocker` fixture, directly from the module - and currently that is not possible, since `_get_mock_module` also expects the pytest config by now).

**Comment by nicoddemus** [comment]
Oh sorry for not replying earlier @blueyed... this got lost on my list of items it seems.

I was wondering if we should just make `mock_module` public, through `mocker.mock_module`. I was not certain about this when I made that refactor, but now I don't see any downside of letting users use it.

What do you think?

**Comment by blueyed** [comment]
Yep, makes sense! 👍

**Comment by blueyed** [comment]
Should I do a PR, or will you handle it?

**Comment by nicoddemus** [comment]
Don't worry, I will handle it tomorrow and make a quick release, but thanks for the offer!
