### ISSUE TITLE
Enable testing asyncio coroutines

### ISSUE THREAD

**Issue by progovoy** [pytest-dev/pytest-mock#75]

**Comment by nicoddemus** [comment]
Hi @progovoy, could you be more specific?

For testing `asyncio` there's the [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio) plugin.

**Comment by progovoy** [comment]
Hi @nicoddemus ,
I am aware of the pytest-asyncio. I was referring to mocking courtliness support just like other methods.
What additional information do you need for me to provide you with?

**Comment by nicoddemus** [comment]
I guess you can mock a coroutine function with another coroutine function, no? Also, does the standard `mock` package support it and `pytest-mock` is not exposing the functionality currently?

It would help also to provide a small example, thanks.

**Comment by nicoddemus** [comment]
Closing for lack of feedback.
