### ISSUE TITLE
Usage examples are really needed.

### ISSUE THREAD

**Issue by gtzampanakis** [pytest-dev/pytest-mock#82]
The README is extensive but does not a single runnable example.

**Comment by jkomusin** [comment]
I just ran the `test_spy` example locally, and there appear to be plenty of other example that should be runnable, is there something in particular you're needing or that's failing to run?

**Comment by gtzampanakis** [comment]
I think the README should show a complete file that can be run with pytest. The file should include fixture creation and a test that uses the fixture.

**Comment by nicoddemus** [comment]
How about the example used in the *usage* section?

```python
def test_foo(mocker):
    # all valid calls
    mocker.patch('os.remove')
    mocker.patch.object(os, 'listdir', autospec=True)
    mocked_isfile = mocker.patch('os.path.isfile')
```

Aside from missing a `import os`, it is directly runnable.

**Comment by gtzampanakis** [comment]
I see now. I didn't know that the ```mocker``` variable is passed in magically. Maybe this should be explained because I spent half an hour trying to find how the hell the ```mocker``` is created.

**Comment by nicoddemus** [comment]
That's how fixtures work with pytest, you can read more about that in the [pytest's docs](https://docs.pytest.org/en/latest/getting-started.html#going-functional-requesting-a-unique-temporary-directory). I have improved the example usage so it is runnable now, thanks for the tip. Any other suggestions are welcome!
