### ISSUE TITLE
Patched objects created with mocker don't work with a mock manager

### ISSUE THREAD

**Issue by dangitall** [pytest-dev/pytest-mock#83]
It seems like when I try to attach patched objects from pytest-mock to a manager mock with `attach_mock`, calls to the patched object are not propagated to the manager's `mock_calls`.

For example,

```
from mock import Mock, patch, call
import os


@patch('os.listdir')
def test_decorator(mock_listdir):
    mgr = Mock()
    mgr.attach_mock(mock_listdir, "listdir")

    os.listdir()

    assert mgr.mock_calls == [call.listdir()]


def test_mocker(mocker):
    mock_listdir = mocker.patch("os.listdir")
    mgr = Mock()
    mgr.attach_mock(mock_listdir, "listdir")

    os.listdir()

    assert mgr.mock_calls == [call.listdir()] 
```

The first test passes but the second fails with:
```
E       assert [] == [call.listdir()]
E         Right contains more items, first extra item: call.listdir()
E         Use -v to get the full diff
```

I'm guessing this is probably an issue with `mock_attach` but thought I'd start here first to see if anyone had any ideas.

I'm running 3.6.1 and
```mock==2.0.0
pbr==3.0.0
py==1.4.33
pytest==3.0.7
pytest-mock==1.6.0
six==1.10.0```

**Comment by nicoddemus** [comment]
Hi, thanks for the report.

Interestingly, running your example but changing from `mock` to `unittest.mock` the 2 tests pass for me, but using your example as it is with the latest `mock` I see the same error.

Printing `mock_listdir` in the two tests gives me the same `MagicMock` object:

```
$ pytest test_foo.py -sq
<MagicMock name='listdir' id='60597296'>
.<MagicMock name='listdir' id='60661648'>
F
```

So I will have to investigate this a little more to understand what's happening.

**Comment by nicoddemus** [comment]
To make `pytest-mock` use the standalone `mock` module, please set this in your `pytest.ini` file:

```ini
[pytest]
mock_use_standalone_module = true
```

Now `pytest-mock` will use the `mock` instead of `unittest.mock` and your example works for me.
