### ISSUE TITLE
Comparing sqla.types

### ISSUE THREAD

**Issue by KaiDriessen** [pytest-dev/pytest-mock#95]
Comparing sqla.types seems to be causing some problems. Output (-vv):

> to_sql_mock.assert_called_once_with(table, mysql_connection.engine, if_exists='append', dtype=dtypes)
E       AssertionError: Expected call: to_sql('table', 'engine', dtype={'var_name': VARCHAR(length=255)}, if_exists='append')
E       Actual call: to_sql('table', 'engine', dtype={'var_name': VARCHAR(length=255)}, if_exists='append')
E       
E       pytest introspection follows:
E       
E       Kwargs:
E       assert {'dtype': {'v...ts': 'append'} == {'dtype': {'va...ts': 'append'}
E         Common items:
E         {'if_exists': 'append'}
E         Differing items:
E         {'dtype': {'var_name': VARCHAR(length=255)}} != {'dtype': {'var_name': VARCHAR(length=255)}}
E         Full diff:
E         {'dtype': {'var_name': VARCHAR(length=255)}, 'if_exists': 'append'}

Replacing the VARCHAR type with any other basic type fixes the problem. The type VARCHAR is obtained as follows:

`import sqlalchemy as sqla`
`sqla.types.VARCHAR(length=255)`

**Comment by nicoddemus** [comment]
Hi @KaiDriessen,

`pytest-mock` is only a thin wrapper around the builtin `unittest.mock` package, so this seems to be an issue with the underlying library. I suggest you to post in [testing-cabal/mock](https://github.com/testing-cabal/mock/issues) instead (feel free to link back to this issue).
